<script lang="ts">
	import { untrack } from 'svelte'; import type { PageProps } from './$types'; import { CompanySectionCard, Input, Select, Switch, i18n } from '$lib';
	let { data }: PageProps = $props(); let values = $state(untrack(() => ({ ...data.section, fid_parametros_tipo_persona_fiscal: data.section.fid_parametros_tipo_persona_fiscal ?? '', fid_parametros_tipo_documento_fiscal: data.section.fid_parametros_tipo_documento_fiscal ?? '', fid_parametros_responsabilidad_fiscal: data.section.fid_parametros_responsabilidad_fiscal ?? '' }))); let baseline = $state(JSON.stringify(values)); const valid = $derived(true); const dirty = $derived(JSON.stringify(values) !== baseline);
</script>
<CompanySectionCard title="Perfil fiscal" subtitle="Entidad legal principal de Perú preparada para facturación electrónica con SUNAT." {valid} {dirty} onSaved={() => baseline = JSON.stringify(values)}>
	<div class="col-span-4 max-[700px]:col-span-12"><Select name="fid_parametros_tipo_persona_fiscal" label="Tipo de persona" bind:value={values.fid_parametros_tipo_persona_fiscal}><option value="">Selecciona un tipo</option>{#each data.catalogos.tipos_persona_fiscal as tipo (tipo.id_parametros)}<option value={tipo.id_parametros}>{tipo.etiqueta}</option>{/each}</Select></div>
	<div class="col-span-4 max-[700px]:col-span-12"><Select name="fid_parametros_tipo_documento_fiscal" label="Tipo de documento" bind:value={values.fid_parametros_tipo_documento_fiscal}><option value="">Selecciona un tipo</option>{#each data.catalogos.tipos_documento as tipo (tipo.id_parametros)}<option value={tipo.id_parametros}>{tipo.etiqueta}</option>{/each}</Select></div><div class="col-span-4 max-[700px]:col-span-12"><Input name="fiscal_numero_documento" label="Número de documento" bind:value={values.fiscal_numero_documento} maxlength={30} /></div>
	<div class="col-span-8 max-[700px]:col-span-12"><Input name="fiscal_razon_social" label="Razón social o nombre" bind:value={values.fiscal_razon_social} maxlength={150} /></div><div class="col-span-4 flex items-end max-[700px]:col-span-12"><div class="flex min-h-16 w-full items-center justify-between gap-4 rounded-md border border-hairline bg-surface px-4 py-3"><div><p class="text-sm font-semibold text-ink">{i18n.t('companies.fiscal.taxable')}</p><p class="mt-0.5 text-xs leading-relaxed text-steel">{i18n.t('companies.fiscal.taxableHelp')}</p></div><Switch name="fiscal_afecto_igv" bind:checked={values.fiscal_afecto_igv} label={i18n.t('companies.fiscal.taxable')} /></div></div>
	<div class="col-span-6 max-[700px]:col-span-12"><Select name="fid_parametros_responsabilidad_fiscal" label="Responsabilidad fiscal" bind:value={values.fid_parametros_responsabilidad_fiscal}><option value="">Selecciona una responsabilidad</option>{#each data.catalogos.responsabilidades_fiscales as item (item.id_parametros)}<option value={item.id_parametros}>{item.etiqueta}</option>{/each}</Select></div><div class="col-span-6 max-[700px]:col-span-12"><Input name="fiscal_telefono" label="Teléfono de contacto" bind:value={values.fiscal_telefono} maxlength={30} /></div>
	<div class="col-span-6 max-[700px]:col-span-12"><Input name="fiscal_correo" label="Correo de contacto" type="email" bind:value={values.fiscal_correo} maxlength={120} /></div><div class="col-span-6 max-[700px]:col-span-12"><Input name="fiscal_direccion" label="Dirección fiscal" bind:value={values.fiscal_direccion} maxlength={250} /></div>
</CompanySectionCard>
