CREATE TABLE configuracion.categorias_pruebas_laboratorio (
  id_categorias_pruebas_laboratorio uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo varchar(80) NOT NULL UNIQUE,
  nombre varchar(140) NOT NULL,
  orden integer NOT NULL DEFAULT 0,
  estado integer NOT NULL DEFAULT 1 CHECK (estado IN (0, 1)),
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text
);
CREATE INDEX categorias_pruebas_laboratorio_estado_idx ON configuracion.categorias_pruebas_laboratorio(estado, orden, nombre);
CREATE TRIGGER establecer_updated_at BEFORE UPDATE ON configuracion.categorias_pruebas_laboratorio FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();

CREATE TABLE configuracion.catalogo_pruebas_laboratorio_base (
  id_catalogo_pruebas_laboratorio_base uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fid_categorias_pruebas_laboratorio uuid NOT NULL REFERENCES configuracion.categorias_pruebas_laboratorio(id_categorias_pruebas_laboratorio) ON DELETE RESTRICT,
  nombre varchar(220) NOT NULL,
  orden integer NOT NULL DEFAULT 0,
  estado integer NOT NULL DEFAULT 1 CHECK (estado IN (0, 1)),
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text,
  CONSTRAINT catalogo_pruebas_laboratorio_base_nombre_check CHECK (char_length(btrim(nombre)) BETWEEN 2 AND 220)
);
CREATE INDEX catalogo_pruebas_laboratorio_base_categoria_idx ON configuracion.catalogo_pruebas_laboratorio_base(fid_categorias_pruebas_laboratorio, estado, orden);
CREATE UNIQUE INDEX catalogo_pruebas_laboratorio_base_unique ON configuracion.catalogo_pruebas_laboratorio_base(fid_categorias_pruebas_laboratorio, upper(btrim(nombre)));
CREATE TRIGGER establecer_updated_at BEFORE UPDATE ON configuracion.catalogo_pruebas_laboratorio_base FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();

WITH datos(categoria, nombre) AS (VALUES
    ('SEROLOGIAS EN CANINOS', 'Brúcela canis 2-Mercaptoetanol'),
    ('SEROLOGIAS EN CANINOS', 'Brúcela canis Inmunocromatografía (ANIGEN )'),
    ('SEROLOGIAS EN CANINOS', 'Ehrlichia canis ACS (ANIGEN)'),
    ('SEROLOGIAS EN CANINOS', 'Ehrlichia canis ACS (SNAP 6 microorganismos, IDEXX)'),
    ('SEROLOGIAS EN CANINOS', 'Ehrlichia canis en Frotis sanguíneo Ehrlichia canis - Anaplasma (ANIGEN)'),
    ('SEROLOGIAS EN CANINOS', 'Leptospira MAT (8 serovares)'),
    ('SEROLOGIAS EN CANINOS', 'Leptospira Prueba prueba rápida inmunocomb'),
    ('SEROLOGIAS EN CANINOS', 'Moquillo canino (Distemper) Antígeno inmunocromatografía'),
    ('SEROLOGIAS EN CANINOS', 'Neospora caninum (Inmunofluoresencia IFA)'),
    ('SEROLOGIAS EN CANINOS', 'Parvovirus canino Antígeno'),
    ('SEROLOGIAS EN CANINOS', 'Toxoplasma Gondi IgG - IgM (inmuno cromatografía)'),
    ('SEROLOGIAS EN CANINOS', 'Prueba rapida de Giardia - Inmunocromatografía'),
    ('SEROLOGIAS EN CANINOS', 'Serología anticuerpos rabia'),
    ('QUÍMICA SANGÚINEA', 'Albúmina'),
    ('QUÍMICA SANGÚINEA', 'Amilasa pancreática'),
    ('QUÍMICA SANGÚINEA', 'Alanino amino transferasa ALT / GPT'),
    ('QUÍMICA SANGÚINEA', 'Anticuerpos Rabia (Remitido Universidad KANSAS / USA)'),
    ('QUÍMICA SANGÚINEA', 'Ácido Fólico'),
    ('QUÍMICA SANGÚINEA', 'Ácido Láctico'),
    ('QUÍMICA SANGÚINEA', 'Ácido Úrico'),
    ('QUÍMICA SANGÚINEA', 'Aldosterona'),
    ('QUÍMICA SANGÚINEA', 'Aspartato amino Transferasa AST/ GOT'),
    ('QUÍMICA SANGÚINEA', 'Bilirrubina Directa'),
    ('QUÍMICA SANGÚINEA', 'Bilirrubina Total'),
    ('QUÍMICA SANGÚINEA', 'Calcio'),
    ('QUÍMICA SANGÚINEA', 'Calcio Iónico'),
    ('QUÍMICA SANGÚINEA', 'Carbamazepina (Niveles)'),
    ('QUÍMICA SANGÚINEA', 'Cloro'),
    ('QUÍMICA SANGÚINEA', 'Colesterol HDL'),
    ('QUÍMICA SANGÚINEA', 'Colesterol Total'),
    ('QUÍMICA SANGÚINEA', 'Colinesterasa'),
    ('QUÍMICA SANGÚINEA', 'Creatin Fosfoquinasa CPK'),
    ('QUÍMICA SANGÚINEA', 'Creatinina'),
    ('QUÍMICA SANGÚINEA', 'Dimetil Arginina Simétrica SDMA ( Ver perfil SDMA 1-2)'),
    ('QUÍMICA SANGÚINEA', 'Fenobarbital (Niveles)'),
    ('QUÍMICA SANGÚINEA', 'Fibrinógeno'),
    ('QUÍMICA SANGÚINEA', 'Fosfatasa Alkalina ALP'),
    ('QUÍMICA SANGÚINEA', 'Fósforo'),
    ('QUÍMICA SANGÚINEA', 'Fructosamina'),
    ('QUÍMICA SANGÚINEA', 'Gama Glutamil Transferasa GGT'),
    ('QUÍMICA SANGÚINEA', 'Glicemia'),
    ('QUÍMICA SANGÚINEA', 'Hemoglobina Glicosilada'),
    ('QUÍMICA SANGÚINEA', 'Insulina (Quimioluminiscencia)'),
    ('QUÍMICA SANGÚINEA', 'InmunoGlobulina G IgG'),
    ('QUÍMICA SANGÚINEA', 'InmunoGlobulina M IgM'),
    ('QUÍMICA SANGÚINEA', 'Ionograma (Sodio/ Cloro/ Potasio/ Ca2/ pH )'),
    ('QUÍMICA SANGÚINEA', 'LDH Deshidrogenasa Láctica'),
    ('QUÍMICA SANGÚINEA', 'Lipasa Pancreática cuantitativa ( No específica )'),
    ('QUÍMICA SANGÚINEA', 'Lipasa Pancreática específica Canina (Semicuantitativa)'),
    ('QUÍMICA SANGÚINEA', 'Magnesio'),
    ('QUÍMICA SANGÚINEA', 'Nitrógeno Ureico BUN'),
    ('QUÍMICA SANGÚINEA', 'Potasio'),
    ('QUÍMICA SANGÚINEA', 'Proteína C Reactiva PCR Cuantitativa'),
    ('QUÍMICA SANGÚINEA', 'Proteínas Totales (Plasmáticas - Séricas)'),
    ('QUÍMICA SANGÚINEA', 'Proteínas Diferenciadas: Albúmina + Globulina + Prot. Totales'),
    ('QUÍMICA SANGÚINEA', 'Prolactina'),
    ('QUÍMICA SANGÚINEA', 'Sodio'),
    ('QUÍMICA SANGÚINEA', 'Triglicéridos'),
    ('QUÍMICA SANGÚINEA', 'Urea'),
    ('QUÍMICA SANGÚINEA', 'Vitamina B-12 (Ciancobalamina)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Peritonitis Infecciosa Felina PIF ELISA'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Peritonitis Infecciosa Felina IFA (Inmunofluoresencia IFA)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Perf Inmunológico Felino I (Sida y leucemia felina) ANIGEN'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Perf Inmunológico Felino II (Sida +leucemia felina) SNAP - IDEXX'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Toxoplasma Gondi IgG - IgM (inmuno cromatografía)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Toxoplasma Gondi IgG'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Toxoplasma Gondi IgM'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Triple viral Felina Inmunocomb'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Panleucopenia Felina en materia fecal (inmunocomatrografia)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Prueba rapida de Giardia - Inmunocromatografía'),
    ('PERFILES MÁS USADOS', 'PERFIL DE CHEQUEO I (Hemograma+Alt+Creatinina+Glucosa)'),
    ('PERFILES MÁS USADOS', 'PERFIL DE CHEQUEO II (Hemograma+Alt+Ast+Fosfatasa alcalina ALP)'),
    ('PERFILES MÁS USADOS', 'PERFIL DE CHEQUEO III (Hemograma+Ast+Ggt+Glucosa+Proteinas Séricas)'),
    ('PERFILES MÁS USADOS', 'PERFIL RENAL I (Bun+Urea+Creatinina+Citoquimicode Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL RENAL II (Hemograma+Creatinina+Urea+Bun)'),
    ('PERFILES MÁS USADOS', 'PERFIL SDMA1 (SDMA+ Creatinina)'),
    ('PERFILES MÁS USADOS', 'PERFIL SDMA2 (SDMA + Creatinina+ Citoquimico de Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL RENAL III (Hemograma+Creatinina+Urea+Bun+C. Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO I (Hemograma+Alt+Creatinina)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO II (Hemograma+Alt+Creatinina+TP+TPT)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO III (Hemograma+Alt+Creatinina+Fa+Bun+TP+TPT)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO IV (Hemograma+Alt+Creatinina+TP oTPT)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO I (Alt+BilTotal+Bil Dir.+Fosfatasa Alk)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO II (Alt+Ggt+BilTotal+Bil Dir.+Proteinas Sericas+Albumina)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO III (Alt+Ggt+Ast+Fa +BilTotal+Bil Dir.)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO IV (Alt+Ggt+Ast+Fa +Proteinas Diferenciadas)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO V (Alt+Ggt+Ast+Fa + Proteínas Diferenciadas+Bilirrubinas)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO I (T4 Libre+Colesterol)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO II (T4 Libre+Colesterol+Triglicéridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO III (T4 Libre+T4Total+Colesterol+Triglicéridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO IV (TSH+T4 Libre)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO V (TSH+T4 Libre+T4 Total)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO VI (TSH específica + T4 Libre)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO VII (TSH específica + T4 Libre + T4 total + Trigliceridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL BIENES GERIATRI (Hemogr+Creatinina+Alt+Gli+Colt+Urea+Bun+T4L+F.AIk+C. Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL GERIATRICO I (Hemograma+Colesterol+Glucosa+Alt+C. Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL GERIATRICO II (Hemog+Colesterol+Glucosa+Alt+Creat+Urea+Bun+C.Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO I (Hemograma+Raspado de piel+Fa)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO II (Hemograma+Rasp de piel+Fa+T4L o Total+Colest)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO III (Hemograma+Rasp de piel+Fa+T4L+Cortisol 2Muestras)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO IV Raspado de piel+citología de piel+cultivo bacteriológico'),
    ('PERFILES MÁS USADOS', 'PERFIL PANCREATICO I (Glicemia+Amilasa+Upasa)'),
    ('PERFILES MÁS USADOS', 'PERFIL PANCREATICO II (Hemograma+Amilasa+Lipasa+Coprograma)'),
    ('PERFILES MÁS USADOS', 'PERFIL DIABETICO I (Glucosa+Citoquimico+Hemoglobina Glicosilada+Fructosamina)'),
    ('PERFILES MÁS USADOS', 'PERFIL DIABETICO II (Citoquimico de Orina+Glucosa)'),
    ('PERFILES MÁS USADOS', 'PERFIL DIABETICO III (Citoquimico de Orina+Glucosa+Fructosamina)'),
    ('PERFILES MÁS USADOS', 'PERFIL DX INSULINOMA ( Glucosa+ Insulina)'),
    ('PERFILES MÁS USADOS', 'PERFIL LIPIDICO I (Colesterol total+Triglicéridos+Glicemia)'),
    ('PERFILES MÁS USADOS', 'PERFIL LIPIDICO II (Col total+Col Hdl+Triglicéridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL MUSCULOESQUELETICO I (AST+CPK+COrina+Hemograma)'),
    ('PERFILES MÁS USADOS', 'PERFIL MUSCULOESQUELETICO II (AST+CPK+COrina+LDH)'),
    ('PERFILES MÁS USADOS', 'PERFIL CONVULSIVO ( Hemograma+Perfil Hepático II y lll+Bun+Urea+Creat+Gluc)'),
    ('PERFILES MÁS USADOS', 'PERFIL CARDIACO (Hemog+Ast+Creat+Urea+Bun+C.Orina+Potasio+Calcio)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEMOPARAS (Hemog+Extend para Hemop+Hemop capa blanca+Técnica de Knott)'),
    ('PERFILES MÁS USADOS', 'PERFIL METABOLICO (Glicemia+Urea+Bun+Colesterol+Ca+P+Mg)'),
    ('PERFILES MÁS USADOS', 'PERFIL REPRODUCTIVO EN CANINOS (Progesterona+Citologia Vaginal)'),
    ('PERFILES MÁS USADOS', 'PERFIL BASICO (Hemograma+Coprologico)'),
    ('PERFILES MÁS USADOS', 'VALORACION EJE HIPOFISIS-ADRENALES (Supresión-Dexa) 3 Muestras'),
    ('PERFILES MÁS USADOS', 'VALORACION EJE HIPOFISIS-ADRENALES (Estimulación ActH) 2 Muestras'),
    ('PERFILES MÁS USADOS', 'PERFIL SUPER PREMIUM ADULTOS (Bilirrubina Total y Directa, creatinina, Alt, T4L, Citoquimico, Coprologico, Hlg)'),
    ('PARASITOLOGIA VETERINARIA', 'Coloración de gram para materia fecal'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico: Directo+ Flotación (Técnica Flotación en sln salina saturada)'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico; Directo+ Flotación.(Técnica Mc. Master)'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico+Fasciola hepática (Técnica de Parfitt y Banks)'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico+Parásitos pulmonares (Técnica Baerman)'),
    ('PARASITOLOGIA VETERINARIA', 'Coproscópico/coprograma (Coprológico, Azucares reductores, pH, sangre oculta)'),
    ('PARASITOLOGIA VETERINARIA', 'Identificación de Fasciola Hepática (Técnica de Parfitt y Banks)'),
    ('PARASITOLOGIA VETERINARIA', 'Identificación de Parásitos Pulmonares (Técnica Baerman)'),
    ('PARASITOLOGIA VETERINARIA', 'Trichograma'),
    ('PARASITOLOGIA VETERINARIA', 'Rapado de piel (Análisis directo KOH y ácaros)'),
    ('MICROBIOLOGIA TRADICIONAL - PERFILES', 'Perfil microbiológico piel: cultivo, identifi. Y antibiog. (MIC) bacteriológico+ cultivo micológico'),
    ('MICROBIOLOGIA TRADICIONAL - PERFILES', 'Perfil microbiológico otras secreciones:'),
    ('MICROBIOLOGIA TRADICIONAL - PERFILES', 'Cultivo, identifi. Y antibio. (MIC) bacteriológico+ cultivo micoiógico'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Coloración de gram en cualquier secreción'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Secreción uterina'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Leche (cada cuarto)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Materia fecal (salmonella sp y shigella sp)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Orina'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Cultivo de sangre (hemocultivo)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Otras muestras clínicas (secreciones, líquidos corporales)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo e identificación de levaduras por Microscan'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Perfil microbiológíco secreción uterina: Cultivo, identifi. Y antibiog. (MIC) bacteriológico + cultivo micológico (levaduras) por Microscan'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Perfil microbiológico de leche: Cultivo, identificación y antibiograma (MIC) bacteriológico + cultivo micológico (levaduras) por Microscan'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Cultivo, identificación y antibiograma (Kirby Bauer)'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Coloración de gram en cualquier secreción'),
    ('MICROBIOLOGIA - TRADICIONAL', '1 oído cultivo, identifi. Y antibiograma bacteriológico + levaduras'),
    ('MICROBIOLOGIA - TRADICIONAL', '2 oídos cultivo, identifi. Y antibiograma bacteriológico + levaduras'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Orina, (urocultivo cuantitativo) cultivo, identificación y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Piel. Cultivo, identificación y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Materia fecal. ( coprocultivo). Cultivo, identifi. Y antibiograma -salmonella sp y shigella sp'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Sangre, (hemocultivo). Cultivo, identificación y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Otras muestras clínicas! (secreciones, líquidos corporales.) Cultivo, identifica y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Antibiograma adicional (Kirby Bauer)'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Cultivo, identificación y antibiograma (Kirby Bauer) bacteriológico + micoiógico'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Cultivo micoiógico (hongos)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Cultivo bacteriológico, identifi. Y antibiog. Usando Microscan (identifi. De genero /especie +antibio. Por mic)'),
    ('MICROBIOLOGIA - MICROSCAN', '1 oído cultivo, identifi. Y antibiograma (MIC) bacteriológico + levaduras'),
    ('MICROBIOLOGIA - MICROSCAN', '2 oídos cultivo, identifi. Y antibiograma (MIC) bacteriológico + levaduras'),
    ('MICROBIOLOGIA - MICROSCAN', 'Orina. Urocultivo cuantitativo y antibiograma (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Piel. Cultivo, identificación y antibiograma (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Materia fecal, (coprocultivo). Cultivo, identifi. Y antibiograma (M\C)-salmonella sp y shigella sp'),
    ('MICROBIOLOGIA - MICROSCAN', 'Sangre, (hemocultivo). Cultivo, identificación y antibiograma (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Otras muestras clínicas: (Secreciones, líquidos corporales,) cultivo, identific. y antibiog. (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Antibiograma adicional (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Cultivo e identificación de levaduras (Microscan)'),
    ('HORMONAS', 'Cortisol'),
    ('HORMONAS', 'Estradiol'),
    ('HORMONAS', 'Hormona adrenocorticotropica ACTH'),
    ('HORMONAS', 'Hormona Estimulante de la tiroides TSH ELISA-Específica Canina'),
    ('HORMONAS', 'Hormona Estimulante de la tiroides TSH ELISA'),
    ('HORMONAS', 'Hormona Folículo Estimulante FSH'),
    ('HORMONAS', 'Hormona Luteinizante LH'),
    ('HORMONAS', 'Hormona TiroxinaT4 Libre ELISA'),
    ('HORMONAS', 'Hormona TiroxinaT4 Total ELISA'),
    ('HORMONAS', 'Hormona Triyodotironina T3 Total (Elisa)'),
    ('HORMONAS', 'Insulina (Quimioluminiscemcia)'),
    ('HORMONAS', 'Progesterona: 1 Muestra (Quimioluminiscencia)'),
    ('HORMONAS', 'Progesterona: 2 Muestras en adelante'),
    ('HORMONAS', 'Testosterona libre'),
    ('HORMONAS', 'Testosterona Total'),
    ('HEMOPARASITOS', 'Hemoparásitos en capa blanca - (Mascotas)'),
    ('HEMOPARASITOS', 'Hemop.mascotas: Babesia, Ehrlichia, Haemobart, Anaplasma,Trypanosoma, Diro'),
    ('HEMOPARASITOS', 'Hemop.bovinos: Babesia, Anaplasma,Trypanosoma (Técnica: extendido de sangre con tinción de wrigth)'),
    ('HEMOPARASITOS', 'Hemop.equinos: Babesia,Trypanosoma, Theileria (Técnica: extendido de sangre con tinción de wrigth)'),
    ('HEMATOLOGIA VETERINARIA', 'Hematocrito'),
    ('HEMATOLOGIA VETERINARIA', 'Hemograma completo + prot totales plasm + reticulocltos'),
    ('HEMATOLOGIA VETERINARIA', 'Plasma rico en plaquetas en equinos (Obtención a partir de sangre citrato)'),
    ('HEMATOLOGIA VETERINARIA', 'Plasma rico en plaquetas en caninos (Obtención a partir de sangre citrato)'),
    ('HEMATOLOGIA VETERINARIA', 'Prueba de Knott para microfilarias'),
    ('HEMATOLOGIA VETERINARIA', 'Suero autólogo (Obtención a partir de tubo seco)'),
    ('HEMATOLOGIA VETERINARIA', 'Test de Compatibilidad Cruzada en caninos'),
    ('COAGULACION', 'Tiempo de Protrombina TP'),
    ('COAGULACION', 'Tiempo parcial deTromboplastina TPT'),
    ('COAGULACION', 'Fibrinógeno'),
    ('CITOLOGIA VETERINARIA', 'Citología (Infección, vaginal, tumoral, IncluyeTVT) Cualquier muestra'),
    ('CITOLOGIA VETERINARIA', 'Citología Vaginal Canina (Ciclo estral)'),
    ('CITOLOGIA VETERINARIA', 'Citología Uterina en Yeguas'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Citoquímico de orina incluye proteinuria y creatinuria'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Directo de fluido vaginal y/o lavado prepucial'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Espermograma (semen total y pajilla) en grandes especies'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Espermograma en pequeñas especies'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de aspirado transtraqueal (citológico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido broncoalveolar (citológico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido cefaloraquídeo (citológico + fisicoquímico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido ruminal'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido sinovial (citológico + fisicoquímico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido abdominal'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Analisisde liquido Torácico')
), categorias AS (
  SELECT categoria, row_number() OVER (ORDER BY categoria) AS orden FROM (SELECT DISTINCT categoria FROM datos) unicas
)
INSERT INTO configuracion.categorias_pruebas_laboratorio (codigo, nombre, orden, created_by, updated_by)
SELECT 'lab_' || substr(md5(categoria), 1, 12), categoria, orden, 'migration', 'migration' FROM categorias;

WITH datos(categoria, nombre) AS (VALUES
    ('SEROLOGIAS EN CANINOS', 'Brúcela canis 2-Mercaptoetanol'),
    ('SEROLOGIAS EN CANINOS', 'Brúcela canis Inmunocromatografía (ANIGEN )'),
    ('SEROLOGIAS EN CANINOS', 'Ehrlichia canis ACS (ANIGEN)'),
    ('SEROLOGIAS EN CANINOS', 'Ehrlichia canis ACS (SNAP 6 microorganismos, IDEXX)'),
    ('SEROLOGIAS EN CANINOS', 'Ehrlichia canis en Frotis sanguíneo Ehrlichia canis - Anaplasma (ANIGEN)'),
    ('SEROLOGIAS EN CANINOS', 'Leptospira MAT (8 serovares)'),
    ('SEROLOGIAS EN CANINOS', 'Leptospira Prueba prueba rápida inmunocomb'),
    ('SEROLOGIAS EN CANINOS', 'Moquillo canino (Distemper) Antígeno inmunocromatografía'),
    ('SEROLOGIAS EN CANINOS', 'Neospora caninum (Inmunofluoresencia IFA)'),
    ('SEROLOGIAS EN CANINOS', 'Parvovirus canino Antígeno'),
    ('SEROLOGIAS EN CANINOS', 'Toxoplasma Gondi IgG - IgM (inmuno cromatografía)'),
    ('SEROLOGIAS EN CANINOS', 'Prueba rapida de Giardia - Inmunocromatografía'),
    ('SEROLOGIAS EN CANINOS', 'Serología anticuerpos rabia'),
    ('QUÍMICA SANGÚINEA', 'Albúmina'),
    ('QUÍMICA SANGÚINEA', 'Amilasa pancreática'),
    ('QUÍMICA SANGÚINEA', 'Alanino amino transferasa ALT / GPT'),
    ('QUÍMICA SANGÚINEA', 'Anticuerpos Rabia (Remitido Universidad KANSAS / USA)'),
    ('QUÍMICA SANGÚINEA', 'Ácido Fólico'),
    ('QUÍMICA SANGÚINEA', 'Ácido Láctico'),
    ('QUÍMICA SANGÚINEA', 'Ácido Úrico'),
    ('QUÍMICA SANGÚINEA', 'Aldosterona'),
    ('QUÍMICA SANGÚINEA', 'Aspartato amino Transferasa AST/ GOT'),
    ('QUÍMICA SANGÚINEA', 'Bilirrubina Directa'),
    ('QUÍMICA SANGÚINEA', 'Bilirrubina Total'),
    ('QUÍMICA SANGÚINEA', 'Calcio'),
    ('QUÍMICA SANGÚINEA', 'Calcio Iónico'),
    ('QUÍMICA SANGÚINEA', 'Carbamazepina (Niveles)'),
    ('QUÍMICA SANGÚINEA', 'Cloro'),
    ('QUÍMICA SANGÚINEA', 'Colesterol HDL'),
    ('QUÍMICA SANGÚINEA', 'Colesterol Total'),
    ('QUÍMICA SANGÚINEA', 'Colinesterasa'),
    ('QUÍMICA SANGÚINEA', 'Creatin Fosfoquinasa CPK'),
    ('QUÍMICA SANGÚINEA', 'Creatinina'),
    ('QUÍMICA SANGÚINEA', 'Dimetil Arginina Simétrica SDMA ( Ver perfil SDMA 1-2)'),
    ('QUÍMICA SANGÚINEA', 'Fenobarbital (Niveles)'),
    ('QUÍMICA SANGÚINEA', 'Fibrinógeno'),
    ('QUÍMICA SANGÚINEA', 'Fosfatasa Alkalina ALP'),
    ('QUÍMICA SANGÚINEA', 'Fósforo'),
    ('QUÍMICA SANGÚINEA', 'Fructosamina'),
    ('QUÍMICA SANGÚINEA', 'Gama Glutamil Transferasa GGT'),
    ('QUÍMICA SANGÚINEA', 'Glicemia'),
    ('QUÍMICA SANGÚINEA', 'Hemoglobina Glicosilada'),
    ('QUÍMICA SANGÚINEA', 'Insulina (Quimioluminiscencia)'),
    ('QUÍMICA SANGÚINEA', 'InmunoGlobulina G IgG'),
    ('QUÍMICA SANGÚINEA', 'InmunoGlobulina M IgM'),
    ('QUÍMICA SANGÚINEA', 'Ionograma (Sodio/ Cloro/ Potasio/ Ca2/ pH )'),
    ('QUÍMICA SANGÚINEA', 'LDH Deshidrogenasa Láctica'),
    ('QUÍMICA SANGÚINEA', 'Lipasa Pancreática cuantitativa ( No específica )'),
    ('QUÍMICA SANGÚINEA', 'Lipasa Pancreática específica Canina (Semicuantitativa)'),
    ('QUÍMICA SANGÚINEA', 'Magnesio'),
    ('QUÍMICA SANGÚINEA', 'Nitrógeno Ureico BUN'),
    ('QUÍMICA SANGÚINEA', 'Potasio'),
    ('QUÍMICA SANGÚINEA', 'Proteína C Reactiva PCR Cuantitativa'),
    ('QUÍMICA SANGÚINEA', 'Proteínas Totales (Plasmáticas - Séricas)'),
    ('QUÍMICA SANGÚINEA', 'Proteínas Diferenciadas: Albúmina + Globulina + Prot. Totales'),
    ('QUÍMICA SANGÚINEA', 'Prolactina'),
    ('QUÍMICA SANGÚINEA', 'Sodio'),
    ('QUÍMICA SANGÚINEA', 'Triglicéridos'),
    ('QUÍMICA SANGÚINEA', 'Urea'),
    ('QUÍMICA SANGÚINEA', 'Vitamina B-12 (Ciancobalamina)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Peritonitis Infecciosa Felina PIF ELISA'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Peritonitis Infecciosa Felina IFA (Inmunofluoresencia IFA)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Perf Inmunológico Felino I (Sida y leucemia felina) ANIGEN'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Perf Inmunológico Felino II (Sida +leucemia felina) SNAP - IDEXX'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Toxoplasma Gondi IgG - IgM (inmuno cromatografía)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Toxoplasma Gondi IgG'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Toxoplasma Gondi IgM'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Triple viral Felina Inmunocomb'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Panleucopenia Felina en materia fecal (inmunocomatrografia)'),
    ('PRUEBAS SEROLOGICAS EN FELINOS', 'Prueba rapida de Giardia - Inmunocromatografía'),
    ('PERFILES MÁS USADOS', 'PERFIL DE CHEQUEO I (Hemograma+Alt+Creatinina+Glucosa)'),
    ('PERFILES MÁS USADOS', 'PERFIL DE CHEQUEO II (Hemograma+Alt+Ast+Fosfatasa alcalina ALP)'),
    ('PERFILES MÁS USADOS', 'PERFIL DE CHEQUEO III (Hemograma+Ast+Ggt+Glucosa+Proteinas Séricas)'),
    ('PERFILES MÁS USADOS', 'PERFIL RENAL I (Bun+Urea+Creatinina+Citoquimicode Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL RENAL II (Hemograma+Creatinina+Urea+Bun)'),
    ('PERFILES MÁS USADOS', 'PERFIL SDMA1 (SDMA+ Creatinina)'),
    ('PERFILES MÁS USADOS', 'PERFIL SDMA2 (SDMA + Creatinina+ Citoquimico de Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL RENAL III (Hemograma+Creatinina+Urea+Bun+C. Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO I (Hemograma+Alt+Creatinina)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO II (Hemograma+Alt+Creatinina+TP+TPT)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO III (Hemograma+Alt+Creatinina+Fa+Bun+TP+TPT)'),
    ('PERFILES MÁS USADOS', 'PERFIL PREQUIRURGICO IV (Hemograma+Alt+Creatinina+TP oTPT)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO I (Alt+BilTotal+Bil Dir.+Fosfatasa Alk)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO II (Alt+Ggt+BilTotal+Bil Dir.+Proteinas Sericas+Albumina)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO III (Alt+Ggt+Ast+Fa +BilTotal+Bil Dir.)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO IV (Alt+Ggt+Ast+Fa +Proteinas Diferenciadas)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEPÁTICO V (Alt+Ggt+Ast+Fa + Proteínas Diferenciadas+Bilirrubinas)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO I (T4 Libre+Colesterol)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO II (T4 Libre+Colesterol+Triglicéridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO III (T4 Libre+T4Total+Colesterol+Triglicéridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO IV (TSH+T4 Libre)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO V (TSH+T4 Libre+T4 Total)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO VI (TSH específica + T4 Libre)'),
    ('PERFILES MÁS USADOS', 'PERFIL TIROIDEO VII (TSH específica + T4 Libre + T4 total + Trigliceridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL BIENES GERIATRI (Hemogr+Creatinina+Alt+Gli+Colt+Urea+Bun+T4L+F.AIk+C. Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL GERIATRICO I (Hemograma+Colesterol+Glucosa+Alt+C. Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL GERIATRICO II (Hemog+Colesterol+Glucosa+Alt+Creat+Urea+Bun+C.Orina)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO I (Hemograma+Raspado de piel+Fa)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO II (Hemograma+Rasp de piel+Fa+T4L o Total+Colest)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO III (Hemograma+Rasp de piel+Fa+T4L+Cortisol 2Muestras)'),
    ('PERFILES MÁS USADOS', 'PERFIL DERMATOLOGICO IV Raspado de piel+citología de piel+cultivo bacteriológico'),
    ('PERFILES MÁS USADOS', 'PERFIL PANCREATICO I (Glicemia+Amilasa+Upasa)'),
    ('PERFILES MÁS USADOS', 'PERFIL PANCREATICO II (Hemograma+Amilasa+Lipasa+Coprograma)'),
    ('PERFILES MÁS USADOS', 'PERFIL DIABETICO I (Glucosa+Citoquimico+Hemoglobina Glicosilada+Fructosamina)'),
    ('PERFILES MÁS USADOS', 'PERFIL DIABETICO II (Citoquimico de Orina+Glucosa)'),
    ('PERFILES MÁS USADOS', 'PERFIL DIABETICO III (Citoquimico de Orina+Glucosa+Fructosamina)'),
    ('PERFILES MÁS USADOS', 'PERFIL DX INSULINOMA ( Glucosa+ Insulina)'),
    ('PERFILES MÁS USADOS', 'PERFIL LIPIDICO I (Colesterol total+Triglicéridos+Glicemia)'),
    ('PERFILES MÁS USADOS', 'PERFIL LIPIDICO II (Col total+Col Hdl+Triglicéridos)'),
    ('PERFILES MÁS USADOS', 'PERFIL MUSCULOESQUELETICO I (AST+CPK+COrina+Hemograma)'),
    ('PERFILES MÁS USADOS', 'PERFIL MUSCULOESQUELETICO II (AST+CPK+COrina+LDH)'),
    ('PERFILES MÁS USADOS', 'PERFIL CONVULSIVO ( Hemograma+Perfil Hepático II y lll+Bun+Urea+Creat+Gluc)'),
    ('PERFILES MÁS USADOS', 'PERFIL CARDIACO (Hemog+Ast+Creat+Urea+Bun+C.Orina+Potasio+Calcio)'),
    ('PERFILES MÁS USADOS', 'PERFIL HEMOPARAS (Hemog+Extend para Hemop+Hemop capa blanca+Técnica de Knott)'),
    ('PERFILES MÁS USADOS', 'PERFIL METABOLICO (Glicemia+Urea+Bun+Colesterol+Ca+P+Mg)'),
    ('PERFILES MÁS USADOS', 'PERFIL REPRODUCTIVO EN CANINOS (Progesterona+Citologia Vaginal)'),
    ('PERFILES MÁS USADOS', 'PERFIL BASICO (Hemograma+Coprologico)'),
    ('PERFILES MÁS USADOS', 'VALORACION EJE HIPOFISIS-ADRENALES (Supresión-Dexa) 3 Muestras'),
    ('PERFILES MÁS USADOS', 'VALORACION EJE HIPOFISIS-ADRENALES (Estimulación ActH) 2 Muestras'),
    ('PERFILES MÁS USADOS', 'PERFIL SUPER PREMIUM ADULTOS (Bilirrubina Total y Directa, creatinina, Alt, T4L, Citoquimico, Coprologico, Hlg)'),
    ('PARASITOLOGIA VETERINARIA', 'Coloración de gram para materia fecal'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico: Directo+ Flotación (Técnica Flotación en sln salina saturada)'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico; Directo+ Flotación.(Técnica Mc. Master)'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico+Fasciola hepática (Técnica de Parfitt y Banks)'),
    ('PARASITOLOGIA VETERINARIA', 'Coprológico+Parásitos pulmonares (Técnica Baerman)'),
    ('PARASITOLOGIA VETERINARIA', 'Coproscópico/coprograma (Coprológico, Azucares reductores, pH, sangre oculta)'),
    ('PARASITOLOGIA VETERINARIA', 'Identificación de Fasciola Hepática (Técnica de Parfitt y Banks)'),
    ('PARASITOLOGIA VETERINARIA', 'Identificación de Parásitos Pulmonares (Técnica Baerman)'),
    ('PARASITOLOGIA VETERINARIA', 'Trichograma'),
    ('PARASITOLOGIA VETERINARIA', 'Rapado de piel (Análisis directo KOH y ácaros)'),
    ('MICROBIOLOGIA TRADICIONAL - PERFILES', 'Perfil microbiológico piel: cultivo, identifi. Y antibiog. (MIC) bacteriológico+ cultivo micológico'),
    ('MICROBIOLOGIA TRADICIONAL - PERFILES', 'Perfil microbiológico otras secreciones:'),
    ('MICROBIOLOGIA TRADICIONAL - PERFILES', 'Cultivo, identifi. Y antibio. (MIC) bacteriológico+ cultivo micoiógico'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Coloración de gram en cualquier secreción'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Secreción uterina'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Leche (cada cuarto)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Materia fecal (salmonella sp y shigella sp)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Orina'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Cultivo de sangre (hemocultivo)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo bacteriológico: Otras muestras clínicas (secreciones, líquidos corporales)'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Cultivo e identificación de levaduras por Microscan'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Perfil microbiológíco secreción uterina: Cultivo, identifi. Y antibiog. (MIC) bacteriológico + cultivo micológico (levaduras) por Microscan'),
    ('MICROBIOLOGIA GRANDES ESPECIES - MICROSCAN', 'Perfil microbiológico de leche: Cultivo, identificación y antibiograma (MIC) bacteriológico + cultivo micológico (levaduras) por Microscan'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Cultivo, identificación y antibiograma (Kirby Bauer)'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Coloración de gram en cualquier secreción'),
    ('MICROBIOLOGIA - TRADICIONAL', '1 oído cultivo, identifi. Y antibiograma bacteriológico + levaduras'),
    ('MICROBIOLOGIA - TRADICIONAL', '2 oídos cultivo, identifi. Y antibiograma bacteriológico + levaduras'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Orina, (urocultivo cuantitativo) cultivo, identificación y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Piel. Cultivo, identificación y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Materia fecal. ( coprocultivo). Cultivo, identifi. Y antibiograma -salmonella sp y shigella sp'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Sangre, (hemocultivo). Cultivo, identificación y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Otras muestras clínicas! (secreciones, líquidos corporales.) Cultivo, identifica y antibiograma'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Antibiograma adicional (Kirby Bauer)'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Cultivo, identificación y antibiograma (Kirby Bauer) bacteriológico + micoiógico'),
    ('MICROBIOLOGIA - TRADICIONAL', 'Cultivo micoiógico (hongos)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Cultivo bacteriológico, identifi. Y antibiog. Usando Microscan (identifi. De genero /especie +antibio. Por mic)'),
    ('MICROBIOLOGIA - MICROSCAN', '1 oído cultivo, identifi. Y antibiograma (MIC) bacteriológico + levaduras'),
    ('MICROBIOLOGIA - MICROSCAN', '2 oídos cultivo, identifi. Y antibiograma (MIC) bacteriológico + levaduras'),
    ('MICROBIOLOGIA - MICROSCAN', 'Orina. Urocultivo cuantitativo y antibiograma (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Piel. Cultivo, identificación y antibiograma (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Materia fecal, (coprocultivo). Cultivo, identifi. Y antibiograma (M\C)-salmonella sp y shigella sp'),
    ('MICROBIOLOGIA - MICROSCAN', 'Sangre, (hemocultivo). Cultivo, identificación y antibiograma (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Otras muestras clínicas: (Secreciones, líquidos corporales,) cultivo, identific. y antibiog. (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Antibiograma adicional (MIC)'),
    ('MICROBIOLOGIA - MICROSCAN', 'Cultivo e identificación de levaduras (Microscan)'),
    ('HORMONAS', 'Cortisol'),
    ('HORMONAS', 'Estradiol'),
    ('HORMONAS', 'Hormona adrenocorticotropica ACTH'),
    ('HORMONAS', 'Hormona Estimulante de la tiroides TSH ELISA-Específica Canina'),
    ('HORMONAS', 'Hormona Estimulante de la tiroides TSH ELISA'),
    ('HORMONAS', 'Hormona Folículo Estimulante FSH'),
    ('HORMONAS', 'Hormona Luteinizante LH'),
    ('HORMONAS', 'Hormona TiroxinaT4 Libre ELISA'),
    ('HORMONAS', 'Hormona TiroxinaT4 Total ELISA'),
    ('HORMONAS', 'Hormona Triyodotironina T3 Total (Elisa)'),
    ('HORMONAS', 'Insulina (Quimioluminiscemcia)'),
    ('HORMONAS', 'Progesterona: 1 Muestra (Quimioluminiscencia)'),
    ('HORMONAS', 'Progesterona: 2 Muestras en adelante'),
    ('HORMONAS', 'Testosterona libre'),
    ('HORMONAS', 'Testosterona Total'),
    ('HEMOPARASITOS', 'Hemoparásitos en capa blanca - (Mascotas)'),
    ('HEMOPARASITOS', 'Hemop.mascotas: Babesia, Ehrlichia, Haemobart, Anaplasma,Trypanosoma, Diro'),
    ('HEMOPARASITOS', 'Hemop.bovinos: Babesia, Anaplasma,Trypanosoma (Técnica: extendido de sangre con tinción de wrigth)'),
    ('HEMOPARASITOS', 'Hemop.equinos: Babesia,Trypanosoma, Theileria (Técnica: extendido de sangre con tinción de wrigth)'),
    ('HEMATOLOGIA VETERINARIA', 'Hematocrito'),
    ('HEMATOLOGIA VETERINARIA', 'Hemograma completo + prot totales plasm + reticulocltos'),
    ('HEMATOLOGIA VETERINARIA', 'Plasma rico en plaquetas en equinos (Obtención a partir de sangre citrato)'),
    ('HEMATOLOGIA VETERINARIA', 'Plasma rico en plaquetas en caninos (Obtención a partir de sangre citrato)'),
    ('HEMATOLOGIA VETERINARIA', 'Prueba de Knott para microfilarias'),
    ('HEMATOLOGIA VETERINARIA', 'Suero autólogo (Obtención a partir de tubo seco)'),
    ('HEMATOLOGIA VETERINARIA', 'Test de Compatibilidad Cruzada en caninos'),
    ('COAGULACION', 'Tiempo de Protrombina TP'),
    ('COAGULACION', 'Tiempo parcial deTromboplastina TPT'),
    ('COAGULACION', 'Fibrinógeno'),
    ('CITOLOGIA VETERINARIA', 'Citología (Infección, vaginal, tumoral, IncluyeTVT) Cualquier muestra'),
    ('CITOLOGIA VETERINARIA', 'Citología Vaginal Canina (Ciclo estral)'),
    ('CITOLOGIA VETERINARIA', 'Citología Uterina en Yeguas'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Citoquímico de orina incluye proteinuria y creatinuria'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Directo de fluido vaginal y/o lavado prepucial'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Espermograma (semen total y pajilla) en grandes especies'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Espermograma en pequeñas especies'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de aspirado transtraqueal (citológico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido broncoalveolar (citológico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido cefaloraquídeo (citológico + fisicoquímico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido ruminal'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido sinovial (citológico + fisicoquímico)'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Análisis de líquido abdominal'),
    ('ANALISIS DE LIQUIDOS Y OTROS', 'Analisisde liquido Torácico')
)
INSERT INTO configuracion.catalogo_pruebas_laboratorio_base (fid_categorias_pruebas_laboratorio, nombre, orden, created_by, updated_by)
SELECT categoria.id_categorias_pruebas_laboratorio, datos.nombre,
       row_number() OVER (PARTITION BY datos.categoria ORDER BY datos.nombre), 'migration', 'migration'
FROM datos JOIN configuracion.categorias_pruebas_laboratorio categoria ON categoria.nombre = datos.categoria;

CREATE TABLE nucleo.pruebas_laboratorio (
  id_pruebas_laboratorio uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fid_organizaciones uuid NOT NULL,
  fid_categorias_pruebas_laboratorio uuid NOT NULL,
  nombre varchar(220) NOT NULL,
  estado integer NOT NULL DEFAULT 1 CHECK (estado IN (0, 1)),
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text,
  eliminado_en timestamptz(3),
  eliminado_por uuid,
  CONSTRAINT pruebas_laboratorio_nombre_check CHECK (char_length(btrim(nombre)) BETWEEN 2 AND 220),
  CONSTRAINT pruebas_laboratorio_organizacion_fk FOREIGN KEY (fid_organizaciones) REFERENCES nucleo.organizaciones(id_organizaciones) ON DELETE CASCADE,
  CONSTRAINT pruebas_laboratorio_categoria_fk FOREIGN KEY (fid_categorias_pruebas_laboratorio) REFERENCES configuracion.categorias_pruebas_laboratorio(id_categorias_pruebas_laboratorio) ON DELETE RESTRICT,
  CONSTRAINT pruebas_laboratorio_id_organizacion_unique UNIQUE (id_pruebas_laboratorio, fid_organizaciones)
);
CREATE INDEX pruebas_laboratorio_organizacion_idx ON nucleo.pruebas_laboratorio(fid_organizaciones, eliminado_en, estado, created_at DESC);
CREATE INDEX pruebas_laboratorio_categoria_idx ON nucleo.pruebas_laboratorio(fid_categorias_pruebas_laboratorio, estado, nombre);
CREATE UNIQUE INDEX pruebas_laboratorio_nombre_activo_unique ON nucleo.pruebas_laboratorio(fid_organizaciones, fid_categorias_pruebas_laboratorio, upper(btrim(nombre))) WHERE eliminado_en IS NULL;
CREATE TRIGGER establecer_updated_at BEFORE UPDATE ON nucleo.pruebas_laboratorio FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();

INSERT INTO nucleo.pruebas_laboratorio (fid_organizaciones, fid_categorias_pruebas_laboratorio, nombre, created_by, updated_by)
SELECT organizacion.id_organizaciones, base.fid_categorias_pruebas_laboratorio, base.nombre, 'migration', 'migration'
FROM nucleo.organizaciones organizacion CROSS JOIN configuracion.catalogo_pruebas_laboratorio_base base
WHERE organizacion.estado = 1 AND organizacion.eliminado_en IS NULL AND base.estado = 1;

CREATE TABLE personas.pruebas_registro_laboratorio (
  id_pruebas_registro_laboratorio uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fid_organizaciones uuid NOT NULL,
  fid_registros_atencion uuid NOT NULL,
  fid_pruebas_laboratorio uuid NOT NULL,
  fid_usuarios_profesional uuid NOT NULL,
  cantidad integer NOT NULL DEFAULT 1 CHECK (cantidad BETWEEN 1 AND 999),
  orden integer NOT NULL DEFAULT 0 CHECK (orden BETWEEN 0 AND 19),
  estado integer NOT NULL DEFAULT 1 CHECK (estado IN (0, 1)),
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text,
  CONSTRAINT pruebas_registro_laboratorio_id_organizacion_unique UNIQUE (id_pruebas_registro_laboratorio, fid_organizaciones),
  CONSTRAINT pruebas_registro_laboratorio_registro_fk FOREIGN KEY (fid_registros_atencion, fid_organizaciones) REFERENCES personas.registros_atencion(id_registros_atencion, fid_organizaciones) ON DELETE RESTRICT,
  CONSTRAINT pruebas_registro_laboratorio_prueba_fk FOREIGN KEY (fid_pruebas_laboratorio, fid_organizaciones) REFERENCES nucleo.pruebas_laboratorio(id_pruebas_laboratorio, fid_organizaciones) ON DELETE RESTRICT,
  CONSTRAINT pruebas_registro_laboratorio_profesional_fk FOREIGN KEY (fid_usuarios_profesional, fid_organizaciones) REFERENCES seguridad.usuarios(id_usuarios, fid_organizaciones) ON DELETE RESTRICT
);
CREATE INDEX pruebas_registro_laboratorio_registro_idx ON personas.pruebas_registro_laboratorio(fid_registros_atencion, orden);
CREATE INDEX pruebas_registro_laboratorio_prueba_idx ON personas.pruebas_registro_laboratorio(fid_pruebas_laboratorio);
CREATE INDEX pruebas_registro_laboratorio_profesional_idx ON personas.pruebas_registro_laboratorio(fid_usuarios_profesional);
CREATE TRIGGER establecer_updated_at BEFORE UPDATE ON personas.pruebas_registro_laboratorio FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();

ALTER TABLE personas.adjuntos_registro_atencion ADD COLUMN fid_pruebas_registro_laboratorio uuid;
ALTER TABLE personas.adjuntos_registro_atencion ADD CONSTRAINT adjuntos_prueba_laboratorio_tenant_fk
  FOREIGN KEY (fid_pruebas_registro_laboratorio, fid_organizaciones)
  REFERENCES personas.pruebas_registro_laboratorio(id_pruebas_registro_laboratorio, fid_organizaciones) ON DELETE RESTRICT;
CREATE INDEX adjuntos_prueba_laboratorio_idx ON personas.adjuntos_registro_atencion(fid_pruebas_registro_laboratorio, eliminado_en);

UPDATE configuracion.tipos_registro_atencion
SET campos = '[
  {"clave":"fecha","etiqueta_es":"Fecha","etiqueta_en":"Date","tipo":"date","requerido":true},
  {"clave":"pruebas","etiqueta_es":"Pruebas de laboratorio","etiqueta_en":"Laboratory tests","tipo":"list","requerido":true,"max_items":20,"campos":[
    {"clave":"fid_usuarios_profesional","etiqueta_es":"Profesional","etiqueta_en":"Professional","tipo":"uuid","fuente":"usuarios_organizacion","requerido":true},
    {"clave":"fid_pruebas_laboratorio","etiqueta_es":"Prueba / examen","etiqueta_en":"Test / exam","tipo":"uuid","fuente":"pruebas_laboratorio","requerido":true},
    {"clave":"cantidad","etiqueta_es":"Cantidad","etiqueta_en":"Quantity","tipo":"number","requerido":true,"min":1,"max":999},
    {"clave":"cantidad_adjuntos","etiqueta_es":"Resultados adjuntos","etiqueta_en":"Attached results","tipo":"number","requerido":true,"min":0,"max":5}
  ]},
  {"clave":"diagnostico_presuntivo","etiqueta_es":"Diagnóstico presuntivo","etiqueta_en":"Presumptive diagnosis","tipo":"textarea","requerido":false,"max":4000}
]'::jsonb, acepta_adjuntos = true, max_adjuntos = 10, updated_by = 'migration'
WHERE codigo = 'examen_laboratorio';

UPDATE configuracion.modulos SET orden = orden + 10, updated_by = 'migration' WHERE codigo = 'administrator.users' AND orden >= 250;
INSERT INTO configuracion.modulos (id_modulos, codigo, nombre, descripcion, icono, ruta, orden, estado, created_by, updated_by)
VALUES (gen_random_uuid(), 'administrator.laboratory_tests', 'Pruebas de laboratorio', 'Administra las pruebas y categorías disponibles para las atenciones.', 'flask-conical', '/administrator/laboratory-tests', 250, 1, 'migration', 'migration')
ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, descripcion=EXCLUDED.descripcion, icono=EXCLUDED.icono, ruta=EXCLUDED.ruta, fid_modulos_padre=NULL, orden=EXCLUDED.orden, estado=1, updated_at=CURRENT_TIMESTAMP, updated_by='migration';

WITH capacidades(codigo, accion, descripcion) AS (VALUES
 ('administrator.laboratory_tests.read','read','Pruebas de laboratorio: Ver'),
 ('administrator.laboratory_tests.create','create','Pruebas de laboratorio: Crear'),
 ('administrator.laboratory_tests.update','update','Pruebas de laboratorio: Actualizar'),
 ('administrator.laboratory_tests.delete','delete','Pruebas de laboratorio: Eliminar'))
INSERT INTO seguridad.permisos (id_permisos,fid_modulos,codigo,accion,descripcion,estado,created_by,updated_by)
SELECT gen_random_uuid(),m.id_modulos,c.codigo,c.accion,c.descripcion,1,'migration','migration' FROM capacidades c JOIN configuracion.modulos m ON m.codigo='administrator.laboratory_tests'
ON CONFLICT (codigo) DO UPDATE SET fid_modulos=EXCLUDED.fid_modulos,accion=EXCLUDED.accion,descripcion=EXCLUDED.descripcion,estado=1,updated_at=CURRENT_TIMESTAMP,updated_by='migration';
INSERT INTO configuracion.planes_modulos (id_planes_modulos,fid_planes,fid_modulos,estado,created_by,updated_by)
SELECT gen_random_uuid(),p.id_planes,m.id_modulos,1,'migration','migration' FROM configuracion.planes p JOIN configuracion.modulos m ON m.codigo='administrator.laboratory_tests' WHERE p.codigo IN ('BASIC','PREMIUM','FULL','SYSTEM')
ON CONFLICT (fid_planes,fid_modulos) DO UPDATE SET estado=1,updated_at=CURRENT_TIMESTAMP,updated_by='migration';
INSERT INTO seguridad.roles_permisos (id_roles_permisos,fid_roles,fid_permisos,estado,created_by,updated_by)
SELECT gen_random_uuid(),r.id_roles,p.id_permisos,1,'migration','migration' FROM seguridad.roles r CROSS JOIN seguridad.permisos p WHERE r.codigo IN ('ADMIN','SUPERADMIN') AND r.eliminado_en IS NULL AND p.codigo LIKE 'administrator.laboratory_tests.%'
ON CONFLICT (fid_roles,fid_permisos) DO UPDATE SET estado=1,updated_at=CURRENT_TIMESTAMP,updated_by='migration';
