-- Catálogos globales ajenos a un tenant.
CREATE SCHEMA IF NOT EXISTS system;

CREATE TABLE system.paises (
  id_paises uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_iso2 char(2) NOT NULL UNIQUE,
  nombre_es text NOT NULL,
  nombre_en text NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text
);

CREATE TABLE system.zonas_horarias (
  id_zonas_horarias uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre_iana text NOT NULL UNIQUE,
  estado integer NOT NULL DEFAULT 1,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text
);

CREATE TABLE system.paises_zonas_horarias (
  id_paises_zonas_horarias uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fid_paises uuid NOT NULL,
  fid_zonas_horarias uuid NOT NULL,
  estado integer NOT NULL DEFAULT 1,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by text,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text,
  CONSTRAINT paises_zonas_horarias_fid_paises_fkey
    FOREIGN KEY (fid_paises) REFERENCES system.paises(id_paises) ON DELETE CASCADE,
  CONSTRAINT paises_zonas_horarias_fid_zonas_horarias_fkey
    FOREIGN KEY (fid_zonas_horarias) REFERENCES system.zonas_horarias(id_zonas_horarias) ON DELETE CASCADE,
  CONSTRAINT paises_zonas_horarias_fid_paises_fid_zonas_horarias_key
    UNIQUE (fid_paises, fid_zonas_horarias)
);

CREATE INDEX paises_zonas_horarias_fid_zonas_horarias_idx
  ON system.paises_zonas_horarias(fid_zonas_horarias);

INSERT INTO system.paises (
  codigo_iso2,
  nombre_es,
  nombre_en,
  created_by,
  updated_by
)
VALUES
  ('AD', 'Andorra', 'Andorra', 'migration', 'migration'),
  ('AE', 'Emiratos Árabes Unidos', 'United Arab Emirates', 'migration', 'migration'),
  ('AF', 'Afganistán', 'Afghanistan', 'migration', 'migration'),
  ('AG', 'Antigua y Barbuda', 'Antigua & Barbuda', 'migration', 'migration'),
  ('AI', 'Anguila', 'Anguilla', 'migration', 'migration'),
  ('AL', 'Albania', 'Albania', 'migration', 'migration'),
  ('AM', 'Armenia', 'Armenia', 'migration', 'migration'),
  ('AO', 'Angola', 'Angola', 'migration', 'migration'),
  ('AQ', 'Antártida', 'Antarctica', 'migration', 'migration'),
  ('AR', 'Argentina', 'Argentina', 'migration', 'migration'),
  ('AS', 'Samoa Americana', 'American Samoa', 'migration', 'migration'),
  ('AT', 'Austria', 'Austria', 'migration', 'migration'),
  ('AU', 'Australia', 'Australia', 'migration', 'migration'),
  ('AW', 'Aruba', 'Aruba', 'migration', 'migration'),
  ('AX', 'Islas Aland', 'Åland Islands', 'migration', 'migration'),
  ('AZ', 'Azerbaiyán', 'Azerbaijan', 'migration', 'migration'),
  ('BA', 'Bosnia y Herzegovina', 'Bosnia & Herzegovina', 'migration', 'migration'),
  ('BB', 'Barbados', 'Barbados', 'migration', 'migration'),
  ('BD', 'Bangladés', 'Bangladesh', 'migration', 'migration'),
  ('BE', 'Bélgica', 'Belgium', 'migration', 'migration'),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'migration', 'migration'),
  ('BG', 'Bulgaria', 'Bulgaria', 'migration', 'migration'),
  ('BH', 'Baréin', 'Bahrain', 'migration', 'migration'),
  ('BI', 'Burundi', 'Burundi', 'migration', 'migration'),
  ('BJ', 'Benín', 'Benin', 'migration', 'migration'),
  ('BL', 'San Bartolomé', 'St. Barthélemy', 'migration', 'migration'),
  ('BM', 'Bermudas', 'Bermuda', 'migration', 'migration'),
  ('BN', 'Brunéi', 'Brunei', 'migration', 'migration'),
  ('BO', 'Bolivia', 'Bolivia', 'migration', 'migration'),
  ('BQ', 'Caribe neerlandés', 'Caribbean Netherlands', 'migration', 'migration'),
  ('BR', 'Brasil', 'Brazil', 'migration', 'migration'),
  ('BS', 'Bahamas', 'Bahamas', 'migration', 'migration'),
  ('BT', 'Bután', 'Bhutan', 'migration', 'migration'),
  ('BV', 'Isla Bouvet', 'Bouvet Island', 'migration', 'migration'),
  ('BW', 'Botsuana', 'Botswana', 'migration', 'migration'),
  ('BY', 'Bielorrusia', 'Belarus', 'migration', 'migration'),
  ('BZ', 'Belice', 'Belize', 'migration', 'migration'),
  ('CA', 'Canadá', 'Canada', 'migration', 'migration'),
  ('CC', 'Islas Cocos', 'Cocos (Keeling) Islands', 'migration', 'migration'),
  ('CD', 'República Democrática del Congo', 'Congo - Kinshasa', 'migration', 'migration'),
  ('CF', 'República Centroafricana', 'Central African Republic', 'migration', 'migration'),
  ('CG', 'Congo', 'Congo - Brazzaville', 'migration', 'migration'),
  ('CH', 'Suiza', 'Switzerland', 'migration', 'migration'),
  ('CI', 'Côte d’Ivoire', 'Côte d’Ivoire', 'migration', 'migration'),
  ('CK', 'Islas Cook', 'Cook Islands', 'migration', 'migration'),
  ('CL', 'Chile', 'Chile', 'migration', 'migration'),
  ('CM', 'Camerún', 'Cameroon', 'migration', 'migration'),
  ('CN', 'China', 'China', 'migration', 'migration'),
  ('CO', 'Colombia', 'Colombia', 'migration', 'migration'),
  ('CR', 'Costa Rica', 'Costa Rica', 'migration', 'migration'),
  ('CU', 'Cuba', 'Cuba', 'migration', 'migration'),
  ('CV', 'Cabo Verde', 'Cape Verde', 'migration', 'migration'),
  ('CW', 'Curazao', 'Curaçao', 'migration', 'migration'),
  ('CX', 'Isla de Navidad', 'Christmas Island', 'migration', 'migration'),
  ('CY', 'Chipre', 'Cyprus', 'migration', 'migration'),
  ('CZ', 'Chequia', 'Czechia', 'migration', 'migration'),
  ('DE', 'Alemania', 'Germany', 'migration', 'migration'),
  ('DJ', 'Yibuti', 'Djibouti', 'migration', 'migration'),
  ('DK', 'Dinamarca', 'Denmark', 'migration', 'migration'),
  ('DM', 'Dominica', 'Dominica', 'migration', 'migration'),
  ('DO', 'República Dominicana', 'Dominican Republic', 'migration', 'migration'),
  ('DZ', 'Argelia', 'Algeria', 'migration', 'migration'),
  ('EC', 'Ecuador', 'Ecuador', 'migration', 'migration'),
  ('EE', 'Estonia', 'Estonia', 'migration', 'migration'),
  ('EG', 'Egipto', 'Egypt', 'migration', 'migration'),
  ('EH', 'Sáhara Occidental', 'Western Sahara', 'migration', 'migration'),
  ('ER', 'Eritrea', 'Eritrea', 'migration', 'migration'),
  ('ES', 'España', 'Spain', 'migration', 'migration'),
  ('ET', 'Etiopía', 'Ethiopia', 'migration', 'migration'),
  ('FI', 'Finlandia', 'Finland', 'migration', 'migration'),
  ('FJ', 'Fiyi', 'Fiji', 'migration', 'migration'),
  ('FK', 'Islas Malvinas', 'Falkland Islands', 'migration', 'migration'),
  ('FM', 'Micronesia', 'Micronesia', 'migration', 'migration'),
  ('FO', 'Islas Feroe', 'Faroe Islands', 'migration', 'migration'),
  ('FR', 'Francia', 'France', 'migration', 'migration'),
  ('GA', 'Gabón', 'Gabon', 'migration', 'migration'),
  ('GB', 'Reino Unido', 'United Kingdom', 'migration', 'migration'),
  ('GD', 'Granada', 'Grenada', 'migration', 'migration'),
  ('GE', 'Georgia', 'Georgia', 'migration', 'migration'),
  ('GF', 'Guayana Francesa', 'French Guiana', 'migration', 'migration'),
  ('GG', 'Guernesey', 'Guernsey', 'migration', 'migration'),
  ('GH', 'Ghana', 'Ghana', 'migration', 'migration'),
  ('GI', 'Gibraltar', 'Gibraltar', 'migration', 'migration'),
  ('GL', 'Groenlandia', 'Greenland', 'migration', 'migration'),
  ('GM', 'Gambia', 'Gambia', 'migration', 'migration'),
  ('GN', 'Guinea', 'Guinea', 'migration', 'migration'),
  ('GP', 'Guadalupe', 'Guadeloupe', 'migration', 'migration'),
  ('GQ', 'Guinea Ecuatorial', 'Equatorial Guinea', 'migration', 'migration'),
  ('GR', 'Grecia', 'Greece', 'migration', 'migration'),
  ('GS', 'Islas Georgia del Sur y Sandwich del Sur', 'South Georgia & South Sandwich Islands', 'migration', 'migration'),
  ('GT', 'Guatemala', 'Guatemala', 'migration', 'migration'),
  ('GU', 'Guam', 'Guam', 'migration', 'migration'),
  ('GW', 'Guinea-Bisáu', 'Guinea-Bissau', 'migration', 'migration'),
  ('GY', 'Guyana', 'Guyana', 'migration', 'migration'),
  ('HK', 'RAE de Hong Kong (China)', 'Hong Kong SAR China', 'migration', 'migration'),
  ('HM', 'Islas Heard y McDonald', 'Heard & McDonald Islands', 'migration', 'migration'),
  ('HN', 'Honduras', 'Honduras', 'migration', 'migration'),
  ('HR', 'Croacia', 'Croatia', 'migration', 'migration'),
  ('HT', 'Haití', 'Haiti', 'migration', 'migration'),
  ('HU', 'Hungría', 'Hungary', 'migration', 'migration'),
  ('ID', 'Indonesia', 'Indonesia', 'migration', 'migration'),
  ('IE', 'Irlanda', 'Ireland', 'migration', 'migration'),
  ('IL', 'Israel', 'Israel', 'migration', 'migration'),
  ('IM', 'Isla de Man', 'Isle of Man', 'migration', 'migration'),
  ('IN', 'India', 'India', 'migration', 'migration'),
  ('IO', 'Territorio Británico del Océano Índico', 'British Indian Ocean Territory', 'migration', 'migration'),
  ('IQ', 'Irak', 'Iraq', 'migration', 'migration'),
  ('IR', 'Irán', 'Iran', 'migration', 'migration'),
  ('IS', 'Islandia', 'Iceland', 'migration', 'migration'),
  ('IT', 'Italia', 'Italy', 'migration', 'migration'),
  ('JE', 'Jersey', 'Jersey', 'migration', 'migration'),
  ('JM', 'Jamaica', 'Jamaica', 'migration', 'migration'),
  ('JO', 'Jordania', 'Jordan', 'migration', 'migration'),
  ('JP', 'Japón', 'Japan', 'migration', 'migration'),
  ('KE', 'Kenia', 'Kenya', 'migration', 'migration'),
  ('KG', 'Kirguistán', 'Kyrgyzstan', 'migration', 'migration'),
  ('KH', 'Camboya', 'Cambodia', 'migration', 'migration'),
  ('KI', 'Kiribati', 'Kiribati', 'migration', 'migration'),
  ('KM', 'Comoras', 'Comoros', 'migration', 'migration'),
  ('KN', 'San Cristóbal y Nieves', 'St. Kitts & Nevis', 'migration', 'migration'),
  ('KP', 'Corea del Norte', 'North Korea', 'migration', 'migration'),
  ('KR', 'Corea del Sur', 'South Korea', 'migration', 'migration'),
  ('KW', 'Kuwait', 'Kuwait', 'migration', 'migration'),
  ('KY', 'Islas Caimán', 'Cayman Islands', 'migration', 'migration'),
  ('KZ', 'Kazajistán', 'Kazakhstan', 'migration', 'migration'),
  ('LA', 'Laos', 'Laos', 'migration', 'migration'),
  ('LB', 'Líbano', 'Lebanon', 'migration', 'migration'),
  ('LC', 'Santa Lucía', 'St. Lucia', 'migration', 'migration'),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'migration', 'migration'),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'migration', 'migration'),
  ('LR', 'Liberia', 'Liberia', 'migration', 'migration'),
  ('LS', 'Lesoto', 'Lesotho', 'migration', 'migration'),
  ('LT', 'Lituania', 'Lithuania', 'migration', 'migration'),
  ('LU', 'Luxemburgo', 'Luxembourg', 'migration', 'migration'),
  ('LV', 'Letonia', 'Latvia', 'migration', 'migration'),
  ('LY', 'Libia', 'Libya', 'migration', 'migration'),
  ('MA', 'Marruecos', 'Morocco', 'migration', 'migration'),
  ('MC', 'Mónaco', 'Monaco', 'migration', 'migration'),
  ('MD', 'Moldavia', 'Moldova', 'migration', 'migration'),
  ('ME', 'Montenegro', 'Montenegro', 'migration', 'migration'),
  ('MF', 'San Martín', 'St. Martin', 'migration', 'migration'),
  ('MG', 'Madagascar', 'Madagascar', 'migration', 'migration'),
  ('MH', 'Islas Marshall', 'Marshall Islands', 'migration', 'migration'),
  ('MK', 'Macedonia del Norte', 'North Macedonia', 'migration', 'migration'),
  ('ML', 'Mali', 'Mali', 'migration', 'migration'),
  ('MM', 'Myanmar (Birmania)', 'Myanmar (Burma)', 'migration', 'migration'),
  ('MN', 'Mongolia', 'Mongolia', 'migration', 'migration'),
  ('MO', 'RAE de Macao (China)', 'Macao SAR China', 'migration', 'migration'),
  ('MP', 'Islas Marianas del Norte', 'Northern Mariana Islands', 'migration', 'migration'),
  ('MQ', 'Martinica', 'Martinique', 'migration', 'migration'),
  ('MR', 'Mauritania', 'Mauritania', 'migration', 'migration'),
  ('MS', 'Montserrat', 'Montserrat', 'migration', 'migration'),
  ('MT', 'Malta', 'Malta', 'migration', 'migration'),
  ('MU', 'Mauricio', 'Mauritius', 'migration', 'migration'),
  ('MV', 'Maldivas', 'Maldives', 'migration', 'migration'),
  ('MW', 'Malaui', 'Malawi', 'migration', 'migration'),
  ('MX', 'México', 'Mexico', 'migration', 'migration'),
  ('MY', 'Malasia', 'Malaysia', 'migration', 'migration'),
  ('MZ', 'Mozambique', 'Mozambique', 'migration', 'migration'),
  ('NA', 'Namibia', 'Namibia', 'migration', 'migration'),
  ('NC', 'Nueva Caledonia', 'New Caledonia', 'migration', 'migration'),
  ('NE', 'Níger', 'Niger', 'migration', 'migration'),
  ('NF', 'Isla Norfolk', 'Norfolk Island', 'migration', 'migration'),
  ('NG', 'Nigeria', 'Nigeria', 'migration', 'migration'),
  ('NI', 'Nicaragua', 'Nicaragua', 'migration', 'migration'),
  ('NL', 'Países Bajos', 'Netherlands', 'migration', 'migration'),
  ('NO', 'Noruega', 'Norway', 'migration', 'migration'),
  ('NP', 'Nepal', 'Nepal', 'migration', 'migration'),
  ('NR', 'Nauru', 'Nauru', 'migration', 'migration'),
  ('NU', 'Niue', 'Niue', 'migration', 'migration'),
  ('NZ', 'Nueva Zelanda', 'New Zealand', 'migration', 'migration'),
  ('OM', 'Omán', 'Oman', 'migration', 'migration'),
  ('PA', 'Panamá', 'Panama', 'migration', 'migration'),
  ('PE', 'Perú', 'Peru', 'migration', 'migration'),
  ('PF', 'Polinesia Francesa', 'French Polynesia', 'migration', 'migration'),
  ('PG', 'Papúa Nueva Guinea', 'Papua New Guinea', 'migration', 'migration'),
  ('PH', 'Filipinas', 'Philippines', 'migration', 'migration'),
  ('PK', 'Pakistán', 'Pakistan', 'migration', 'migration'),
  ('PL', 'Polonia', 'Poland', 'migration', 'migration'),
  ('PM', 'San Pedro y Miquelón', 'St. Pierre & Miquelon', 'migration', 'migration'),
  ('PN', 'Islas Pitcairn', 'Pitcairn Islands', 'migration', 'migration'),
  ('PR', 'Puerto Rico', 'Puerto Rico', 'migration', 'migration'),
  ('PS', 'Territorios Palestinos', 'Palestinian Territories', 'migration', 'migration'),
  ('PT', 'Portugal', 'Portugal', 'migration', 'migration'),
  ('PW', 'Palaos', 'Palau', 'migration', 'migration'),
  ('PY', 'Paraguay', 'Paraguay', 'migration', 'migration'),
  ('QA', 'Catar', 'Qatar', 'migration', 'migration'),
  ('RE', 'Reunión', 'Réunion', 'migration', 'migration'),
  ('RO', 'Rumanía', 'Romania', 'migration', 'migration'),
  ('RS', 'Serbia', 'Serbia', 'migration', 'migration'),
  ('RU', 'Rusia', 'Russia', 'migration', 'migration'),
  ('RW', 'Ruanda', 'Rwanda', 'migration', 'migration'),
  ('SA', 'Arabia Saudí', 'Saudi Arabia', 'migration', 'migration'),
  ('SB', 'Islas Salomón', 'Solomon Islands', 'migration', 'migration'),
  ('SC', 'Seychelles', 'Seychelles', 'migration', 'migration'),
  ('SD', 'Sudán', 'Sudan', 'migration', 'migration'),
  ('SE', 'Suecia', 'Sweden', 'migration', 'migration'),
  ('SG', 'Singapur', 'Singapore', 'migration', 'migration'),
  ('SH', 'Santa Elena', 'St. Helena', 'migration', 'migration'),
  ('SI', 'Eslovenia', 'Slovenia', 'migration', 'migration'),
  ('SJ', 'Svalbard y Jan Mayen', 'Svalbard & Jan Mayen', 'migration', 'migration'),
  ('SK', 'Eslovaquia', 'Slovakia', 'migration', 'migration'),
  ('SL', 'Sierra Leona', 'Sierra Leone', 'migration', 'migration'),
  ('SM', 'San Marino', 'San Marino', 'migration', 'migration'),
  ('SN', 'Senegal', 'Senegal', 'migration', 'migration'),
  ('SO', 'Somalia', 'Somalia', 'migration', 'migration'),
  ('SR', 'Surinam', 'Suriname', 'migration', 'migration'),
  ('SS', 'Sudán del Sur', 'South Sudan', 'migration', 'migration'),
  ('ST', 'Santo Tomé y Príncipe', 'São Tomé & Príncipe', 'migration', 'migration'),
  ('SV', 'El Salvador', 'El Salvador', 'migration', 'migration'),
  ('SX', 'Sint Maarten', 'Sint Maarten', 'migration', 'migration'),
  ('SY', 'Siria', 'Syria', 'migration', 'migration'),
  ('SZ', 'Esuatini', 'Eswatini', 'migration', 'migration'),
  ('TC', 'Islas Turcas y Caicos', 'Turks & Caicos Islands', 'migration', 'migration'),
  ('TD', 'Chad', 'Chad', 'migration', 'migration'),
  ('TF', 'Territorios Australes Franceses', 'French Southern Territories', 'migration', 'migration'),
  ('TG', 'Togo', 'Togo', 'migration', 'migration'),
  ('TH', 'Tailandia', 'Thailand', 'migration', 'migration'),
  ('TJ', 'Tayikistán', 'Tajikistan', 'migration', 'migration'),
  ('TK', 'Tokelau', 'Tokelau', 'migration', 'migration'),
  ('TL', 'Timor-Leste', 'Timor-Leste', 'migration', 'migration'),
  ('TM', 'Turkmenistán', 'Turkmenistan', 'migration', 'migration'),
  ('TN', 'Túnez', 'Tunisia', 'migration', 'migration'),
  ('TO', 'Tonga', 'Tonga', 'migration', 'migration'),
  ('TR', 'Turquía', 'Türkiye', 'migration', 'migration'),
  ('TT', 'Trinidad y Tobago', 'Trinidad & Tobago', 'migration', 'migration'),
  ('TV', 'Tuvalu', 'Tuvalu', 'migration', 'migration'),
  ('TW', 'Taiwán', 'Taiwan', 'migration', 'migration'),
  ('TZ', 'Tanzania', 'Tanzania', 'migration', 'migration'),
  ('UA', 'Ucrania', 'Ukraine', 'migration', 'migration'),
  ('UG', 'Uganda', 'Uganda', 'migration', 'migration'),
  ('UM', 'Islas menores alejadas de EE. UU.', 'U.S. Outlying Islands', 'migration', 'migration'),
  ('US', 'Estados Unidos', 'United States', 'migration', 'migration'),
  ('UY', 'Uruguay', 'Uruguay', 'migration', 'migration'),
  ('UZ', 'Uzbekistán', 'Uzbekistan', 'migration', 'migration'),
  ('VA', 'Ciudad del Vaticano', 'Vatican City', 'migration', 'migration'),
  ('VC', 'San Vicente y las Granadinas', 'St. Vincent & Grenadines', 'migration', 'migration'),
  ('VE', 'Venezuela', 'Venezuela', 'migration', 'migration'),
  ('VG', 'Islas Vírgenes Británicas', 'British Virgin Islands', 'migration', 'migration'),
  ('VI', 'Islas Vírgenes de EE. UU.', 'U.S. Virgin Islands', 'migration', 'migration'),
  ('VN', 'Vietnam', 'Vietnam', 'migration', 'migration'),
  ('VU', 'Vanuatu', 'Vanuatu', 'migration', 'migration'),
  ('WF', 'Wallis y Futuna', 'Wallis & Futuna', 'migration', 'migration'),
  ('WS', 'Samoa', 'Samoa', 'migration', 'migration'),
  ('YE', 'Yemen', 'Yemen', 'migration', 'migration'),
  ('YT', 'Mayotte', 'Mayotte', 'migration', 'migration'),
  ('ZA', 'Sudáfrica', 'South Africa', 'migration', 'migration'),
  ('ZM', 'Zambia', 'Zambia', 'migration', 'migration'),
  ('ZW', 'Zimbabue', 'Zimbabwe', 'migration', 'migration');

-- PostgreSQL usa la base IANA incluida en su tzdata. Se excluyen únicamente
-- identificadores internos que no representan zonas elegibles por un usuario.
INSERT INTO system.zonas_horarias (
  nombre_iana,
  created_by,
  updated_by
)
SELECT name, 'migration', 'migration'
FROM pg_timezone_names
WHERE name !~ '^(posix|right)/'
  AND name NOT IN ('Factory', 'localtime', 'posixrules')
ORDER BY name;

-- zone.tab vincula las zonas canónicas con su país. El catálogo de zonas conserva
-- también alias IANA, por eso puede contener más filas que esta relación.
INSERT INTO system.paises_zonas_horarias (
  fid_paises,
  fid_zonas_horarias,
  created_by,
  updated_by
)
SELECT
  pais.id_paises,
  zona.id_zonas_horarias,
  'migration',
  'migration'
FROM (
  VALUES
  ('AD', 'Europe/Andorra'),
  ('AE', 'Asia/Dubai'),
  ('AF', 'Asia/Kabul'),
  ('AG', 'America/Antigua'),
  ('AI', 'America/Anguilla'),
  ('AL', 'Europe/Tirane'),
  ('AM', 'Asia/Yerevan'),
  ('AO', 'Africa/Luanda'),
  ('AQ', 'Antarctica/McMurdo'),
  ('AQ', 'Antarctica/Casey'),
  ('AQ', 'Antarctica/Davis'),
  ('AQ', 'Antarctica/DumontDUrville'),
  ('AQ', 'Antarctica/Mawson'),
  ('AQ', 'Antarctica/Palmer'),
  ('AQ', 'Antarctica/Rothera'),
  ('AQ', 'Antarctica/Syowa'),
  ('AQ', 'Antarctica/Troll'),
  ('AQ', 'Antarctica/Vostok'),
  ('AR', 'America/Argentina/Buenos_Aires'),
  ('AR', 'America/Argentina/Cordoba'),
  ('AR', 'America/Argentina/Salta'),
  ('AR', 'America/Argentina/Jujuy'),
  ('AR', 'America/Argentina/Tucuman'),
  ('AR', 'America/Argentina/Catamarca'),
  ('AR', 'America/Argentina/La_Rioja'),
  ('AR', 'America/Argentina/San_Juan'),
  ('AR', 'America/Argentina/Mendoza'),
  ('AR', 'America/Argentina/San_Luis'),
  ('AR', 'America/Argentina/Rio_Gallegos'),
  ('AR', 'America/Argentina/Ushuaia'),
  ('AS', 'Pacific/Pago_Pago'),
  ('AT', 'Europe/Vienna'),
  ('AU', 'Australia/Lord_Howe'),
  ('AU', 'Antarctica/Macquarie'),
  ('AU', 'Australia/Hobart'),
  ('AU', 'Australia/Melbourne'),
  ('AU', 'Australia/Sydney'),
  ('AU', 'Australia/Broken_Hill'),
  ('AU', 'Australia/Brisbane'),
  ('AU', 'Australia/Lindeman'),
  ('AU', 'Australia/Adelaide'),
  ('AU', 'Australia/Darwin'),
  ('AU', 'Australia/Perth'),
  ('AU', 'Australia/Eucla'),
  ('AW', 'America/Aruba'),
  ('AX', 'Europe/Mariehamn'),
  ('AZ', 'Asia/Baku'),
  ('BA', 'Europe/Sarajevo'),
  ('BB', 'America/Barbados'),
  ('BD', 'Asia/Dhaka'),
  ('BE', 'Europe/Brussels'),
  ('BF', 'Africa/Ouagadougou'),
  ('BG', 'Europe/Sofia'),
  ('BH', 'Asia/Bahrain'),
  ('BI', 'Africa/Bujumbura'),
  ('BJ', 'Africa/Porto-Novo'),
  ('BL', 'America/St_Barthelemy'),
  ('BM', 'Atlantic/Bermuda'),
  ('BN', 'Asia/Brunei'),
  ('BO', 'America/La_Paz'),
  ('BQ', 'America/Kralendijk'),
  ('BR', 'America/Noronha'),
  ('BR', 'America/Belem'),
  ('BR', 'America/Fortaleza'),
  ('BR', 'America/Recife'),
  ('BR', 'America/Araguaina'),
  ('BR', 'America/Maceio'),
  ('BR', 'America/Bahia'),
  ('BR', 'America/Sao_Paulo'),
  ('BR', 'America/Campo_Grande'),
  ('BR', 'America/Cuiaba'),
  ('BR', 'America/Santarem'),
  ('BR', 'America/Porto_Velho'),
  ('BR', 'America/Boa_Vista'),
  ('BR', 'America/Manaus'),
  ('BR', 'America/Eirunepe'),
  ('BR', 'America/Rio_Branco'),
  ('BS', 'America/Nassau'),
  ('BT', 'Asia/Thimphu'),
  ('BW', 'Africa/Gaborone'),
  ('BY', 'Europe/Minsk'),
  ('BZ', 'America/Belize'),
  ('CA', 'America/St_Johns'),
  ('CA', 'America/Halifax'),
  ('CA', 'America/Glace_Bay'),
  ('CA', 'America/Moncton'),
  ('CA', 'America/Goose_Bay'),
  ('CA', 'America/Blanc-Sablon'),
  ('CA', 'America/Toronto'),
  ('CA', 'America/Iqaluit'),
  ('CA', 'America/Atikokan'),
  ('CA', 'America/Winnipeg'),
  ('CA', 'America/Resolute'),
  ('CA', 'America/Rankin_Inlet'),
  ('CA', 'America/Regina'),
  ('CA', 'America/Swift_Current'),
  ('CA', 'America/Edmonton'),
  ('CA', 'America/Cambridge_Bay'),
  ('CA', 'America/Inuvik'),
  ('CA', 'America/Vancouver'),
  ('CA', 'America/Creston'),
  ('CA', 'America/Dawson_Creek'),
  ('CA', 'America/Fort_Nelson'),
  ('CA', 'America/Whitehorse'),
  ('CA', 'America/Dawson'),
  ('CC', 'Indian/Cocos'),
  ('CD', 'Africa/Kinshasa'),
  ('CD', 'Africa/Lubumbashi'),
  ('CF', 'Africa/Bangui'),
  ('CG', 'Africa/Brazzaville'),
  ('CH', 'Europe/Zurich'),
  ('CI', 'Africa/Abidjan'),
  ('CK', 'Pacific/Rarotonga'),
  ('CL', 'America/Santiago'),
  ('CL', 'America/Coyhaique'),
  ('CL', 'America/Punta_Arenas'),
  ('CL', 'Pacific/Easter'),
  ('CM', 'Africa/Douala'),
  ('CN', 'Asia/Shanghai'),
  ('CN', 'Asia/Urumqi'),
  ('CO', 'America/Bogota'),
  ('CR', 'America/Costa_Rica'),
  ('CU', 'America/Havana'),
  ('CV', 'Atlantic/Cape_Verde'),
  ('CW', 'America/Curacao'),
  ('CX', 'Indian/Christmas'),
  ('CY', 'Asia/Nicosia'),
  ('CY', 'Asia/Famagusta'),
  ('CZ', 'Europe/Prague'),
  ('DE', 'Europe/Berlin'),
  ('DE', 'Europe/Busingen'),
  ('DJ', 'Africa/Djibouti'),
  ('DK', 'Europe/Copenhagen'),
  ('DM', 'America/Dominica'),
  ('DO', 'America/Santo_Domingo'),
  ('DZ', 'Africa/Algiers'),
  ('EC', 'America/Guayaquil'),
  ('EC', 'Pacific/Galapagos'),
  ('EE', 'Europe/Tallinn'),
  ('EG', 'Africa/Cairo'),
  ('EH', 'Africa/El_Aaiun'),
  ('ER', 'Africa/Asmara'),
  ('ES', 'Europe/Madrid'),
  ('ES', 'Africa/Ceuta'),
  ('ES', 'Atlantic/Canary'),
  ('ET', 'Africa/Addis_Ababa'),
  ('FI', 'Europe/Helsinki'),
  ('FJ', 'Pacific/Fiji'),
  ('FK', 'Atlantic/Stanley'),
  ('FM', 'Pacific/Chuuk'),
  ('FM', 'Pacific/Pohnpei'),
  ('FM', 'Pacific/Kosrae'),
  ('FO', 'Atlantic/Faroe'),
  ('FR', 'Europe/Paris'),
  ('GA', 'Africa/Libreville'),
  ('GB', 'Europe/London'),
  ('GD', 'America/Grenada'),
  ('GE', 'Asia/Tbilisi'),
  ('GF', 'America/Cayenne'),
  ('GG', 'Europe/Guernsey'),
  ('GH', 'Africa/Accra'),
  ('GI', 'Europe/Gibraltar'),
  ('GL', 'America/Nuuk'),
  ('GL', 'America/Danmarkshavn'),
  ('GL', 'America/Scoresbysund'),
  ('GL', 'America/Thule'),
  ('GM', 'Africa/Banjul'),
  ('GN', 'Africa/Conakry'),
  ('GP', 'America/Guadeloupe'),
  ('GQ', 'Africa/Malabo'),
  ('GR', 'Europe/Athens'),
  ('GS', 'Atlantic/South_Georgia'),
  ('GT', 'America/Guatemala'),
  ('GU', 'Pacific/Guam'),
  ('GW', 'Africa/Bissau'),
  ('GY', 'America/Guyana'),
  ('HK', 'Asia/Hong_Kong'),
  ('HN', 'America/Tegucigalpa'),
  ('HR', 'Europe/Zagreb'),
  ('HT', 'America/Port-au-Prince'),
  ('HU', 'Europe/Budapest'),
  ('ID', 'Asia/Jakarta'),
  ('ID', 'Asia/Pontianak'),
  ('ID', 'Asia/Makassar'),
  ('ID', 'Asia/Jayapura'),
  ('IE', 'Europe/Dublin'),
  ('IL', 'Asia/Jerusalem'),
  ('IM', 'Europe/Isle_of_Man'),
  ('IN', 'Asia/Kolkata'),
  ('IO', 'Indian/Chagos'),
  ('IQ', 'Asia/Baghdad'),
  ('IR', 'Asia/Tehran'),
  ('IS', 'Atlantic/Reykjavik'),
  ('IT', 'Europe/Rome'),
  ('JE', 'Europe/Jersey'),
  ('JM', 'America/Jamaica'),
  ('JO', 'Asia/Amman'),
  ('JP', 'Asia/Tokyo'),
  ('KE', 'Africa/Nairobi'),
  ('KG', 'Asia/Bishkek'),
  ('KH', 'Asia/Phnom_Penh'),
  ('KI', 'Pacific/Tarawa'),
  ('KI', 'Pacific/Kanton'),
  ('KI', 'Pacific/Kiritimati'),
  ('KM', 'Indian/Comoro'),
  ('KN', 'America/St_Kitts'),
  ('KP', 'Asia/Pyongyang'),
  ('KR', 'Asia/Seoul'),
  ('KW', 'Asia/Kuwait'),
  ('KY', 'America/Cayman'),
  ('KZ', 'Asia/Almaty'),
  ('KZ', 'Asia/Qyzylorda'),
  ('KZ', 'Asia/Qostanay'),
  ('KZ', 'Asia/Aqtobe'),
  ('KZ', 'Asia/Aqtau'),
  ('KZ', 'Asia/Atyrau'),
  ('KZ', 'Asia/Oral'),
  ('LA', 'Asia/Vientiane'),
  ('LB', 'Asia/Beirut'),
  ('LC', 'America/St_Lucia'),
  ('LI', 'Europe/Vaduz'),
  ('LK', 'Asia/Colombo'),
  ('LR', 'Africa/Monrovia'),
  ('LS', 'Africa/Maseru'),
  ('LT', 'Europe/Vilnius'),
  ('LU', 'Europe/Luxembourg'),
  ('LV', 'Europe/Riga'),
  ('LY', 'Africa/Tripoli'),
  ('MA', 'Africa/Casablanca'),
  ('MC', 'Europe/Monaco'),
  ('MD', 'Europe/Chisinau'),
  ('ME', 'Europe/Podgorica'),
  ('MF', 'America/Marigot'),
  ('MG', 'Indian/Antananarivo'),
  ('MH', 'Pacific/Majuro'),
  ('MH', 'Pacific/Kwajalein'),
  ('MK', 'Europe/Skopje'),
  ('ML', 'Africa/Bamako'),
  ('MM', 'Asia/Yangon'),
  ('MN', 'Asia/Ulaanbaatar'),
  ('MN', 'Asia/Hovd'),
  ('MO', 'Asia/Macau'),
  ('MP', 'Pacific/Saipan'),
  ('MQ', 'America/Martinique'),
  ('MR', 'Africa/Nouakchott'),
  ('MS', 'America/Montserrat'),
  ('MT', 'Europe/Malta'),
  ('MU', 'Indian/Mauritius'),
  ('MV', 'Indian/Maldives'),
  ('MW', 'Africa/Blantyre'),
  ('MX', 'America/Mexico_City'),
  ('MX', 'America/Cancun'),
  ('MX', 'America/Merida'),
  ('MX', 'America/Monterrey'),
  ('MX', 'America/Matamoros'),
  ('MX', 'America/Chihuahua'),
  ('MX', 'America/Ciudad_Juarez'),
  ('MX', 'America/Ojinaga'),
  ('MX', 'America/Mazatlan'),
  ('MX', 'America/Bahia_Banderas'),
  ('MX', 'America/Hermosillo'),
  ('MX', 'America/Tijuana'),
  ('MY', 'Asia/Kuala_Lumpur'),
  ('MY', 'Asia/Kuching'),
  ('MZ', 'Africa/Maputo'),
  ('NA', 'Africa/Windhoek'),
  ('NC', 'Pacific/Noumea'),
  ('NE', 'Africa/Niamey'),
  ('NF', 'Pacific/Norfolk'),
  ('NG', 'Africa/Lagos'),
  ('NI', 'America/Managua'),
  ('NL', 'Europe/Amsterdam'),
  ('NO', 'Europe/Oslo'),
  ('NP', 'Asia/Kathmandu'),
  ('NR', 'Pacific/Nauru'),
  ('NU', 'Pacific/Niue'),
  ('NZ', 'Pacific/Auckland'),
  ('NZ', 'Pacific/Chatham'),
  ('OM', 'Asia/Muscat'),
  ('PA', 'America/Panama'),
  ('PE', 'America/Lima'),
  ('PF', 'Pacific/Tahiti'),
  ('PF', 'Pacific/Marquesas'),
  ('PF', 'Pacific/Gambier'),
  ('PG', 'Pacific/Port_Moresby'),
  ('PG', 'Pacific/Bougainville'),
  ('PH', 'Asia/Manila'),
  ('PK', 'Asia/Karachi'),
  ('PL', 'Europe/Warsaw'),
  ('PM', 'America/Miquelon'),
  ('PN', 'Pacific/Pitcairn'),
  ('PR', 'America/Puerto_Rico'),
  ('PS', 'Asia/Gaza'),
  ('PS', 'Asia/Hebron'),
  ('PT', 'Europe/Lisbon'),
  ('PT', 'Atlantic/Madeira'),
  ('PT', 'Atlantic/Azores'),
  ('PW', 'Pacific/Palau'),
  ('PY', 'America/Asuncion'),
  ('QA', 'Asia/Qatar'),
  ('RE', 'Indian/Reunion'),
  ('RO', 'Europe/Bucharest'),
  ('RS', 'Europe/Belgrade'),
  ('RU', 'Europe/Kaliningrad'),
  ('RU', 'Europe/Moscow'),
  ('UA', 'Europe/Simferopol'),
  ('RU', 'Europe/Kirov'),
  ('RU', 'Europe/Volgograd'),
  ('RU', 'Europe/Astrakhan'),
  ('RU', 'Europe/Saratov'),
  ('RU', 'Europe/Ulyanovsk'),
  ('RU', 'Europe/Samara'),
  ('RU', 'Asia/Yekaterinburg'),
  ('RU', 'Asia/Omsk'),
  ('RU', 'Asia/Novosibirsk'),
  ('RU', 'Asia/Barnaul'),
  ('RU', 'Asia/Tomsk'),
  ('RU', 'Asia/Novokuznetsk'),
  ('RU', 'Asia/Krasnoyarsk'),
  ('RU', 'Asia/Irkutsk'),
  ('RU', 'Asia/Chita'),
  ('RU', 'Asia/Yakutsk'),
  ('RU', 'Asia/Khandyga'),
  ('RU', 'Asia/Vladivostok'),
  ('RU', 'Asia/Ust-Nera'),
  ('RU', 'Asia/Magadan'),
  ('RU', 'Asia/Sakhalin'),
  ('RU', 'Asia/Srednekolymsk'),
  ('RU', 'Asia/Kamchatka'),
  ('RU', 'Asia/Anadyr'),
  ('RW', 'Africa/Kigali'),
  ('SA', 'Asia/Riyadh'),
  ('SB', 'Pacific/Guadalcanal'),
  ('SC', 'Indian/Mahe'),
  ('SD', 'Africa/Khartoum'),
  ('SE', 'Europe/Stockholm'),
  ('SG', 'Asia/Singapore'),
  ('SH', 'Atlantic/St_Helena'),
  ('SI', 'Europe/Ljubljana'),
  ('SJ', 'Arctic/Longyearbyen'),
  ('SK', 'Europe/Bratislava'),
  ('SL', 'Africa/Freetown'),
  ('SM', 'Europe/San_Marino'),
  ('SN', 'Africa/Dakar'),
  ('SO', 'Africa/Mogadishu'),
  ('SR', 'America/Paramaribo'),
  ('SS', 'Africa/Juba'),
  ('ST', 'Africa/Sao_Tome'),
  ('SV', 'America/El_Salvador'),
  ('SX', 'America/Lower_Princes'),
  ('SY', 'Asia/Damascus'),
  ('SZ', 'Africa/Mbabane'),
  ('TC', 'America/Grand_Turk'),
  ('TD', 'Africa/Ndjamena'),
  ('TF', 'Indian/Kerguelen'),
  ('TG', 'Africa/Lome'),
  ('TH', 'Asia/Bangkok'),
  ('TJ', 'Asia/Dushanbe'),
  ('TK', 'Pacific/Fakaofo'),
  ('TL', 'Asia/Dili'),
  ('TM', 'Asia/Ashgabat'),
  ('TN', 'Africa/Tunis'),
  ('TO', 'Pacific/Tongatapu'),
  ('TR', 'Europe/Istanbul'),
  ('TT', 'America/Port_of_Spain'),
  ('TV', 'Pacific/Funafuti'),
  ('TW', 'Asia/Taipei'),
  ('TZ', 'Africa/Dar_es_Salaam'),
  ('UA', 'Europe/Kyiv'),
  ('UG', 'Africa/Kampala'),
  ('UM', 'Pacific/Midway'),
  ('UM', 'Pacific/Wake'),
  ('US', 'America/New_York'),
  ('US', 'America/Detroit'),
  ('US', 'America/Kentucky/Louisville'),
  ('US', 'America/Kentucky/Monticello'),
  ('US', 'America/Indiana/Indianapolis'),
  ('US', 'America/Indiana/Vincennes'),
  ('US', 'America/Indiana/Winamac'),
  ('US', 'America/Indiana/Marengo'),
  ('US', 'America/Indiana/Petersburg'),
  ('US', 'America/Indiana/Vevay'),
  ('US', 'America/Chicago'),
  ('US', 'America/Indiana/Tell_City'),
  ('US', 'America/Indiana/Knox'),
  ('US', 'America/Menominee'),
  ('US', 'America/North_Dakota/Center'),
  ('US', 'America/North_Dakota/New_Salem'),
  ('US', 'America/North_Dakota/Beulah'),
  ('US', 'America/Denver'),
  ('US', 'America/Boise'),
  ('US', 'America/Phoenix'),
  ('US', 'America/Los_Angeles'),
  ('US', 'America/Anchorage'),
  ('US', 'America/Juneau'),
  ('US', 'America/Sitka'),
  ('US', 'America/Metlakatla'),
  ('US', 'America/Yakutat'),
  ('US', 'America/Nome'),
  ('US', 'America/Adak'),
  ('US', 'Pacific/Honolulu'),
  ('UY', 'America/Montevideo'),
  ('UZ', 'Asia/Samarkand'),
  ('UZ', 'Asia/Tashkent'),
  ('VA', 'Europe/Vatican'),
  ('VC', 'America/St_Vincent'),
  ('VE', 'America/Caracas'),
  ('VG', 'America/Tortola'),
  ('VI', 'America/St_Thomas'),
  ('VN', 'Asia/Ho_Chi_Minh'),
  ('VU', 'Pacific/Efate'),
  ('WF', 'Pacific/Wallis'),
  ('WS', 'Pacific/Apia'),
  ('YE', 'Asia/Aden'),
  ('YT', 'Indian/Mayotte'),
  ('ZA', 'Africa/Johannesburg'),
  ('ZM', 'Africa/Lusaka'),
  ('ZW', 'Africa/Harare')
) AS origen(codigo_iso2, nombre_iana)
JOIN system.paises AS pais
  ON pais.codigo_iso2 = origen.codigo_iso2
JOIN system.zonas_horarias AS zona
  ON zona.nombre_iana = origen.nombre_iana;

ALTER TABLE configuracion.preferencias_usuario
  ADD COLUMN fid_paises uuid,
  ADD COLUMN fid_zonas_horarias uuid;

-- Conserva cualquier valor histórico de zona horaria antes de retirar el texto libre.
UPDATE configuracion.preferencias_usuario AS preferencias
SET fid_zonas_horarias = zona.id_zonas_horarias
FROM system.zonas_horarias AS zona
WHERE preferencias.zona_horaria = zona.nombre_iana;

ALTER TABLE configuracion.preferencias_usuario
  DROP COLUMN zona_horaria,
  ADD CONSTRAINT preferencias_usuario_fid_paises_fkey
    FOREIGN KEY (fid_paises) REFERENCES system.paises(id_paises),
  ADD CONSTRAINT preferencias_usuario_fid_zonas_horarias_fkey
    FOREIGN KEY (fid_zonas_horarias) REFERENCES system.zonas_horarias(id_zonas_horarias);

CREATE INDEX preferencias_usuario_fid_paises_idx
  ON configuracion.preferencias_usuario(fid_paises);
CREATE INDEX preferencias_usuario_fid_zonas_horarias_idx
  ON configuracion.preferencias_usuario(fid_zonas_horarias);

CREATE TRIGGER establecer_updated_at
  BEFORE UPDATE ON system.paises
  FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();
CREATE TRIGGER establecer_updated_at
  BEFORE UPDATE ON system.zonas_horarias
  FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();
CREATE TRIGGER establecer_updated_at
  BEFORE UPDATE ON system.paises_zonas_horarias
  FOR EACH ROW EXECUTE FUNCTION configuracion.establecer_updated_at();
