WITH procedimientos(nombre, descripcion_guia) AS (
  VALUES
    ('Extirpación tumores mamarios', 'Registrar la técnica empleada en extirpación tumores mamarios, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción callo postural', 'Registrar la técnica empleada en extracción callo postural, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción de clavos ortopédicos con sedación', 'Registrar la técnica empleada en extracción de clavos ortopédicos con sedación, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción de dientes en profilaxis', 'Registrar la técnica empleada en extracción de dientes en profilaxis, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción de papilomas orales', 'Registrar la técnica empleada en extracción de papilomas orales, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción papilomas palpebrales y meibomas fibrosos', 'Registrar la técnica empleada en extracción papilomas palpebrales y meibomas fibrosos, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción simple canino', 'Registrar la técnica empleada en extracción simple canino, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción simple incisivo', 'Registrar la técnica empleada en extracción simple incisivo, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción simple molar', 'Registrar la técnica empleada en extracción simple molar, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Extracción tumores de piel no mamarios', 'Registrar la técnica empleada en extracción tumores de piel no mamarios, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Faringostomía de alimentacion con sedación', 'Registrar la técnica empleada en faringostomía de alimentacion con sedación, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Fístula', 'Registrar la técnica empleada en fístula, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Flap de tercer parpado', 'Registrar la técnica empleada en flap de tercer parpado, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Gastrectomía parcial', 'Registrar la técnica empleada en gastrectomía parcial, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hemilaminectomia', 'Registrar la técnica empleada en hemilaminectomia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia diafragmatica', 'Registrar la técnica empleada en hernia diafragmatica, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia escrotal', 'Registrar la técnica empleada en hernia escrotal, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia inguinal bilateral', 'Registrar la técnica empleada en hernia inguinal bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia inguinal unilateral', 'Registrar la técnica empleada en hernia inguinal unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia perineal bilateral', 'Registrar la técnica empleada en hernia perineal bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia perineal unilateral', 'Registrar la técnica empleada en hernia perineal unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Hernia umbilical', 'Registrar la técnica empleada en hernia umbilical, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Higroma bilateral', 'Registrar la técnica empleada en higroma bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Higroma unilateral', 'Registrar la técnica empleada en higroma unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Injertos de piel', 'Registrar la técnica empleada en injertos de piel, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Laparoscopia', 'Registrar la técnica empleada en laparoscopia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Laringoscopia', 'Registrar la técnica empleada en laringoscopia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Lavado traqueobronquial', 'Registrar la técnica empleada en lavado traqueobronquial, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Lobectomía hepática', 'Registrar la técnica empleada en lobectomía hepática, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Lobectomía pulmonar', 'Registrar la técnica empleada en lobectomía pulmonar, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Luxación patelar unilateral', 'Registrar la técnica empleada en luxación patelar unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Mastectomía radical', 'Registrar la técnica empleada en mastectomía radical, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Mastectomía unilateral', 'Registrar la técnica empleada en mastectomía unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Menisectomia', 'Registrar la técnica empleada en menisectomia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Mucocele', 'Registrar la técnica empleada en mucocele, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Narinas', 'Registrar la técnica empleada en narinas, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Nefrotomía', 'Registrar la técnica empleada en nefrotomía, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('No union de proceso anconeo', 'Registrar la técnica empleada en no union de proceso anconeo, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Orquiectomía', 'Registrar la técnica empleada en orquiectomía, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteocondritis disecante húmero o codo', 'Registrar la técnica empleada en osteocondritis disecante húmero o codo, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteocondritis disecante húmero o codo bilateral', 'Registrar la técnica empleada en osteocondritis disecante húmero o codo bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de escápula', 'Registrar la técnica empleada en osteosíntesis de escápula, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de fémur', 'Registrar la técnica empleada en osteosíntesis de fémur, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de fémur bilateral', 'Registrar la técnica empleada en osteosíntesis de fémur bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de fractura múltiple de cadera', 'Registrar la técnica empleada en osteosíntesis de fractura múltiple de cadera, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de fractura múltiple de cadera y luxación sacroiliaca', 'Registrar la técnica empleada en osteosíntesis de fractura múltiple de cadera y luxación sacroiliaca, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de húmero', 'Registrar la técnica empleada en osteosíntesis de húmero, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de húmero bilateral', 'Registrar la técnica empleada en osteosíntesis de húmero bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de íleon', 'Registrar la técnica empleada en osteosíntesis de íleon, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de mandíbula', 'Registrar la técnica empleada en osteosíntesis de mandíbula, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de radio', 'Registrar la técnica empleada en osteosíntesis de radio, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de radio bilateral', 'Registrar la técnica empleada en osteosíntesis de radio bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de tibia', 'Registrar la técnica empleada en osteosíntesis de tibia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de tibia bilateral', 'Registrar la técnica empleada en osteosíntesis de tibia bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de ulna', 'Registrar la técnica empleada en osteosíntesis de ulna, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis de ulna bilateral', 'Registrar la técnica empleada en osteosíntesis de ulna bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis intercondilea/supracondilea húmero o fémur', 'Registrar la técnica empleada en osteosíntesis intercondilea/supracondilea húmero o fémur, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis intercondilea/supracondilea húmero o fémur bilateral', 'Registrar la técnica empleada en osteosíntesis intercondilea/supracondilea húmero o fémur bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis luxación sacroiliaca', 'Registrar la técnica empleada en osteosíntesis luxación sacroiliaca, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Osteosíntesis retiro de material', 'Registrar la técnica empleada en osteosíntesis retiro de material, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Otohematoma bilateral', 'Registrar la técnica empleada en otohematoma bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Otohematoma unilateral', 'Registrar la técnica empleada en otohematoma unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Ovariohisterectomía OVH', 'Registrar la técnica empleada en ovariohisterectomía OVH, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Pancreatectomía parcial', 'Registrar la técnica empleada en pancreatectomía parcial, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Pectinectomia', 'Registrar la técnica empleada en pectinectomia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Pericardiectomía', 'Registrar la técnica empleada en pericardiectomía, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Pericardiocentesis', 'Registrar la técnica empleada en pericardiocentesis, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Persistencia arco aórtico', 'Registrar la técnica empleada en persistencia arco aórtico, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Persistencia del ducto arterioso', 'Registrar la técnica empleada en persistencia del ducto arterioso, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Piloroplastia', 'Registrar la técnica empleada en piloroplastia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Piometra caninos', 'Registrar la técnica empleada en piometra caninos, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Plastia en puente', 'Registrar la técnica empleada en plastia en puente, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Plastia por avance', 'Registrar la técnica empleada en plastia por avance, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Queratectomía unilateral', 'Registrar la técnica empleada en queratectomía unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Quimioterapia', 'Registrar la técnica empleada en quimioterapia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Radio curvo bilateral', 'Registrar la técnica empleada en radio curvo bilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Radio curvo unilateral', 'Registrar la técnica empleada en radio curvo unilateral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción abierta de luxación de codo', 'Registrar la técnica empleada en reducción abierta de luxación de codo, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción abierta húmero-escapular', 'Registrar la técnica empleada en reducción abierta húmero-escapular, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción abierta luxación coxo-femoral', 'Registrar la técnica empleada en reducción abierta luxación coxo-femoral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción cerrada de luxación de codo', 'Registrar la técnica empleada en reducción cerrada de luxación de codo, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción cerrada luxación coxo-femoral', 'Registrar la técnica empleada en reducción cerrada luxación coxo-femoral, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción prolapso ocular', 'Registrar la técnica empleada en reducción prolapso ocular, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Reducción prolapso rectal (bolsa de tabaco)', 'Registrar la técnica empleada en reducción prolapso rectal (bolsa de tabaco), los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Rinoscopia', 'Registrar la técnica empleada en rinoscopia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Rinotomía (trepanación)', 'Registrar la técnica empleada en rinotomía (trepanación), los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Ruptura de ligamento cruzado anterior hamaca', 'Registrar la técnica empleada en ruptura de ligamento cruzado anterior hamaca, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Ruptura de ligamento cruzado TPLO osteotomia niveladora de plato tibial', 'Registrar la técnica empleada en ruptura de ligamento cruzado TPLO osteotomia niveladora de plato tibial, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Ruptura de ligamento cruzado TTA avance de la tuberosidad tibial', 'Registrar la técnica empleada en ruptura de ligamento cruzado TTA avance de la tuberosidad tibial, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Sialoadenectomía', 'Registrar la técnica empleada en sialoadenectomía, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('SLOT (hernia discal cervical)', 'Registrar la técnica empleada en sLOT (hernia discal cervical), los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Sondaje caninos', 'Registrar la técnica empleada en sondaje caninos, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Sondaje felinos', 'Registrar la técnica empleada en sondaje felinos, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Suturas de heridas con anestesia general', 'Registrar la técnica empleada en suturas de heridas con anestesia general, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Suturas de heridas con sedación', 'Registrar la técnica empleada en suturas de heridas con sedación, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tarsorrafia', 'Registrar la técnica empleada en tarsorrafia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tenorrafia extensores', 'Registrar la técnica empleada en tenorrafia extensores, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tenotomía flexor digital', 'Registrar la técnica empleada en tenotomía flexor digital, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tirilla de fluoresceina', 'Registrar la técnica empleada en tirilla de fluoresceina, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tirilla de produccion de lagrimas', 'Registrar la técnica empleada en tirilla de produccion de lagrimas, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Toma de muestras para laboratorio', 'Registrar la técnica empleada en toma de muestras para laboratorio, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Toracotomía exploratoria', 'Registrar la técnica empleada en toracotomía exploratoria, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Transfusión sanguínea', 'Registrar la técnica empleada en transfusión sanguínea, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Traqueoscopia', 'Registrar la técnica empleada en traqueoscopia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Traqueostomía permanente con cánula nelaton', 'Registrar la técnica empleada en traqueostomía permanente con cánula nelaton, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Traqueotomía con cánula nelaton', 'Registrar la técnica empleada en traqueotomía con cánula nelaton, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tubo a tórax', 'Registrar la técnica empleada en tubo a tórax, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Tubo a tórax doble', 'Registrar la técnica empleada en tubo a tórax doble, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Uréter ectópico', 'Registrar la técnica empleada en uréter ectópico, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Uretrostomía perineal', 'Registrar la técnica empleada en uretrostomía perineal, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Vaginoscopia', 'Registrar la técnica empleada en vaginoscopia, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Vendaje férula', 'Registrar la técnica empleada en vendaje férula, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Vendaje Robert-Jones', 'Registrar la técnica empleada en vendaje Robert-Jones, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Vendaje simple', 'Registrar la técnica empleada en vendaje simple, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Estabilización lumbosacra por luxo fractura', 'Registrar la técnica empleada en estabilización lumbosacra por luxo fractura, los hallazgos, materiales utilizados, resultado y cuidados indicados.'),
    ('Vulvoplastia', 'Registrar la técnica empleada en vulvoplastia, los hallazgos, materiales utilizados, resultado y cuidados indicados.')
)
INSERT INTO nucleo.procedimientos_veterinarios (
  fid_organizaciones, nombre, descripcion_guia, estado, created_by, updated_by
)
SELECT organizacion.id_organizaciones, procedimiento.nombre,
       procedimiento.descripcion_guia, 1, 'migration', 'migration'
FROM nucleo.organizaciones organizacion
CROSS JOIN procedimientos procedimiento
WHERE organizacion.estado = 1
  AND organizacion.eliminado_en IS NULL
ON CONFLICT (fid_organizaciones, upper(btrim(nombre)))
  WHERE eliminado_en IS NULL
DO UPDATE SET
  descripcion_guia = EXCLUDED.descripcion_guia,
  estado = 1,
  updated_at = CURRENT_TIMESTAMP,
  updated_by = 'migration';

