<script lang="ts">
  import { enhance } from '$app/forms';
  import { goto } from '$app/navigation';
  import { createColumnHelper, createTable, tableFeatures } from '@tanstack/svelte-table';
  import type { SubmitFunction } from '@sveltejs/kit';
  import { toast } from 'svelte-sonner';
  import type { PageProps } from './$types';
  import { Breadcrumb, Button, Card, ConfirmationDialog, Icon, Input, Select, Switch, i18n, tienePermiso } from '$lib';
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
  import CatalogSearch from '$lib/components/CatalogSearch.svelte';
  import CatalogLoadingOverlay from '$lib/components/CatalogLoadingOverlay.svelte';
  import CatalogPagination from '$lib/components/CatalogPagination.svelte';
  import CatalogDuplicateHints from '$lib/components/CatalogDuplicateHints.svelte';

  let { data }: PageProps = $props();
  type Test = (typeof data.pruebas)[number];
  const featureSet = tableFeatures({});
  const columnHelper = createColumnHelper<typeof featureSet, Test>();
  const testsTable = createTable({ features: featureSet, columns: columnHelper.columns([columnHelper.display({ id: 'actions' }), columnHelper.accessor('nombre', { header: 'name' }), columnHelper.display({ id: 'category' }), columnHelper.accessor('estado', { header: 'status' })]), get data() { return data.pruebas; } });
  let selected = $state<Test | null>(null); let editorOpen = $state(false); let deleteOpen = $state(false); let processing = $state(false); let form = $state<HTMLFormElement>(); let action = $state('?/create'); let nombre = $state(''); let categoria = $state('');
  const canCreate = $derived(tienePermiso(data.usuario.permisos, 'administrator.laboratory_tests.create'));
  const canUpdate = $derived(tienePermiso(data.usuario.permisos, 'administrator.laboratory_tests.update'));
  const canDelete = $derived(tienePermiso(data.usuario.permisos, 'administrator.laboratory_tests.delete'));
  const canAny = $derived(canUpdate || canDelete);
  const breadcrumbs = $derived([{ label: i18n.t('nav.dashboard'), href: '/dashboard' }, { label: i18n.t('laboratoryTests.title') }]);

  function edit(item: Test | null) { selected = item; nombre = item?.nombre ?? ''; categoria = item?.fid_categorias_pruebas_laboratorio ?? ''; action = item ? '?/update' : '?/create'; editorOpen = true; }
  const submit: SubmitFunction = () => { processing = true; return async ({ result, update }) => { processing = false; if (result.type === 'success') { if (!selected) await goto('/administrator/laboratory-tests', { invalidateAll: true, noScroll: true, replaceState: true }); else await update({ invalidateAll: true, reset: false }); editorOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('laboratoryTests.saved') }); } else { const message = result.type === 'failure' && typeof result.data?.laboratoryTestMessage === 'string' ? result.data.laboratoryTestMessage : 'laboratoryTests.saveError'; toast.error(i18n.t('notifications.type.error'), { description: i18n.t(message) }); } }; };
  function submitEditor() { form?.requestSubmit(); return Promise.resolve(); }
  async function status(item: Test, active: boolean) { const body = new FormData(); body.set('id', item.id_pruebas_laboratorio); body.set('activo', String(active)); processing = true; const response = await fetch('?/status', { method: 'POST', body }); const result = await response.json(); processing = false; if (response.ok) { await import('$app/navigation').then(({ invalidateAll }) => invalidateAll()); toast.success(i18n.t('notifications.type.success'), { description: i18n.t(active ? 'laboratoryTests.activated' : 'laboratoryTests.deactivated') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t(result?.message ?? 'laboratoryTests.saveError') }); }
  async function remove() { if (!selected) return; const body = new FormData(); body.set('id', selected.id_pruebas_laboratorio); processing = true; const response = await fetch('?/delete', { method: 'POST', body }); processing = false; if (response.ok) { await import('$app/navigation').then(({ invalidateAll }) => invalidateAll()); deleteOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('laboratoryTests.deleted') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t('laboratoryTests.saveError') }); }
</script>

<svelte:head><title>{i18n.t('laboratoryTests.title')} · Sumaq System</title></svelte:head>
<Breadcrumb items={breadcrumbs} />
<section class="flex flex-col gap-5">
  <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-[28px] tracking-[-0.02em] text-ink">{i18n.t('laboratoryTests.title')}</h1><p class="mt-1.5 max-w-[68ch] text-steel">{i18n.t('laboratoryTests.description')}</p></div>{#if canCreate}<Button onclick={() => edit(null)}><Icon name="plus" size={17} />{i18n.t('laboratoryTests.new')}</Button>{/if}</div>
  <CatalogSearch value={data.busqueda} route="/administrator/laboratory-tests" maxLength={220} />
  <Card padding="none" class="relative overflow-hidden"><CatalogLoadingOverlay />
    {#if !data.pruebas.length}<div class="py-14 text-center"><Icon name="flask-conical" size={32} class="mx-auto text-stone" /><p class="mt-3 font-semibold text-ink">{i18n.t('laboratoryTests.empty')}</p></div>
    {:else}<div class="hidden overflow-x-auto md:block"><table class="w-full table-fixed border-collapse text-left text-sm"><colgroup>{#if canAny}<col class="w-[92px]" />{/if}<col /><col class="w-[28%]" /><col class="w-[16%]" /></colgroup><thead class="bg-canvas"><tr class="border-b border-hairline text-[11px] font-bold uppercase tracking-[0.04em] text-ink">{#if canAny}<th class="border-r border-hairline px-3 py-3 text-center">{i18n.t('laboratoryTests.actions')}</th>{/if}<th class="border-r border-hairline px-4 py-3">{i18n.t('laboratoryTests.name')}</th><th class="border-r border-hairline px-4 py-3">{i18n.t('laboratoryTests.category')}</th><th class="px-4 py-3 text-center">{i18n.t('laboratoryTests.status')}</th></tr></thead><tbody>{#each data.pruebas as item (item.id_pruebas_laboratorio)}<tr class="border-b border-hairline odd:bg-surface/55 even:bg-canvas hover:bg-primary-soft/35">{#if canAny}<td class="border-r border-hairline px-2 py-2.5"><div class="flex justify-center gap-1">{#if canUpdate}<button type="button" title={i18n.t('laboratoryTests.edit')} class="grid size-7 place-items-center rounded-md text-steel hover:bg-canvas hover:text-primary" onclick={() => edit(item)}><Icon name="pencil" size={15} /></button>{/if}{#if canDelete}<DropdownMenu.Root><DropdownMenu.Trigger class="grid size-7 place-items-center rounded-md text-steel hover:bg-canvas"><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="start"><DropdownMenu.Item class="text-error focus:bg-error/10 focus:text-error" onSelect={() => { selected = item; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('laboratoryTests.delete')}</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root>{/if}</div></td>{/if}<td class="border-r border-hairline px-4 py-2.5 font-normal text-steel">{item.nombre}</td><td class="border-r border-hairline px-4 py-2.5 font-normal text-steel">{item.categoria.nombre}</td><td class="px-4 py-2.5"><div class="flex justify-center"><Switch checked={item.estado === 1} disabled={!canUpdate || processing} label={`${i18n.t('laboratoryTests.status')}: ${item.nombre}`} onchange={(active) => status(item, active)} /></div></td></tr>{/each}</tbody></table></div>
    <div class="divide-y divide-hairline md:hidden">{#each data.pruebas as item (item.id_pruebas_laboratorio)}<article class="p-4"><div class="flex items-start justify-between gap-3"><div><strong class="text-sm text-ink">{item.nombre}</strong><p class="mt-1 text-xs text-steel">{item.categoria.nombre}</p></div>{#if canAny}<DropdownMenu.Root><DropdownMenu.Trigger class="grid size-8 place-items-center rounded-md text-stone"><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="end">{#if canUpdate}<DropdownMenu.Item onSelect={() => edit(item)}><Icon name="pencil" size={15} />{i18n.t('laboratoryTests.edit')}</DropdownMenu.Item>{/if}{#if canDelete}<DropdownMenu.Item class="text-error" onSelect={() => { selected = item; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('laboratoryTests.delete')}</DropdownMenu.Item>{/if}</DropdownMenu.Content></DropdownMenu.Root>{/if}</div><div class="mt-3 flex items-center gap-2 border-t border-hairline pt-3"><Switch checked={item.estado === 1} disabled={!canUpdate || processing} label={item.nombre} onchange={(active) => status(item, active)} /><span class="text-xs text-steel">{i18n.t(item.estado === 1 ? 'laboratoryTests.active' : 'laboratoryTests.inactive')}</span></div></article>{/each}</div>{/if}
  </Card>
  <CatalogPagination route="/administrator/laboratory-tests" search={data.busqueda} current={data.pruebas.length} total={data.total} previous={data.paginacion.anterior} next={data.paginacion.siguiente} />
</section>

<ConfirmationDialog bind:open={editorOpen} variant="info" icon={selected ? 'pencil' : 'flask-conical'} title={i18n.t(selected ? 'laboratoryTests.editTitle' : 'laboratoryTests.new')} description={i18n.t('laboratoryTests.editorHelp')} confirmLabel={i18n.t('laboratoryTests.save')} cancelLabel={i18n.t('attentions.cancel')} confirmDisabled={processing} onConfirm={submitEditor}><form bind:this={form} method="POST" {action} use:enhance={submit} autocomplete="off" class="grid gap-4 text-left"><input type="hidden" name="id" value={selected?.id_pruebas_laboratorio ?? ''} /><Select name="fid_categorias_pruebas_laboratorio" label={i18n.t('laboratoryTests.category')} bind:value={categoria} required><option value="">{i18n.t('attentions.selectOption')}</option>{#each data.categorias as item (item.id_categorias_pruebas_laboratorio)}<option value={item.id_categorias_pruebas_laboratorio}>{item.nombre}</option>{/each}</Select><div class="relative"><Input name="nombre" autocomplete="off" label={i18n.t('laboratoryTests.name')} bind:value={nombre} required maxlength={220} /><CatalogDuplicateHints query={nombre} endpoint="/administrator/laboratory-tests/search" collection="pruebas" idKey="id_pruebas_laboratorio" secondaryKey="categoria.nombre" disabled={Boolean(selected)} onSelect={(item) => edit(item as Test)} /></div></form></ConfirmationDialog>
<ConfirmationDialog bind:open={deleteOpen} variant="danger" icon="trash-2" title={i18n.t('laboratoryTests.deleteTitle')} description={i18n.t('laboratoryTests.deleteHelp')} confirmLabel={i18n.t('laboratoryTests.delete')} cancelLabel={i18n.t('attentions.cancel')} confirmDisabled={processing} onConfirm={remove} />
