<script lang="ts">
  import { enhance } from '$app/forms';
  import type { SubmitFunction } from '@sveltejs/kit';
  import { toast } from 'svelte-sonner';
  import type { PageProps } from './$types';
  import { Breadcrumb, Button, Card, ConfirmationDialog, Icon, Input, Select, Switch, i18n, tienePermiso } from '$lib';
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';

  let { data }: PageProps = $props();
  type Test = (typeof data.pruebas)[number];
  let selected = $state<Test | null>(null); let editorOpen = $state(false); let deleteOpen = $state(false); let processing = $state(false); let form = $state<HTMLFormElement>(); let action = $state('?/create'); let nombre = $state(''); let categoria = $state('');
  const canCreate = $derived(tienePermiso(data.usuario.permisos, 'administrator.laboratory_tests.create'));
  const canUpdate = $derived(tienePermiso(data.usuario.permisos, 'administrator.laboratory_tests.update'));
  const canDelete = $derived(tienePermiso(data.usuario.permisos, 'administrator.laboratory_tests.delete'));
  const canAny = $derived(canUpdate || canDelete);
  const breadcrumbs = $derived([{ label: i18n.t('nav.dashboard'), href: '/dashboard' }, { label: i18n.t('laboratoryTests.title') }]);

  function edit(item: Test | null) { selected = item; nombre = item?.nombre ?? ''; categoria = item?.fid_categorias_pruebas_laboratorio ?? ''; action = item ? '?/update' : '?/create'; editorOpen = true; }
  const submit: SubmitFunction = () => { processing = true; return async ({ result, update }) => { processing = false; if (result.type === 'success') { await update({ invalidateAll: true, reset: false }); editorOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('laboratoryTests.saved') }); } else { const message = result.type === 'failure' && typeof result.data?.laboratoryTestMessage === 'string' ? result.data.laboratoryTestMessage : 'laboratoryTests.saveError'; toast.error(i18n.t('notifications.type.error'), { description: i18n.t(message) }); } }; };
  function submitEditor() { form?.requestSubmit(); return Promise.resolve(); }
  async function status(item: Test, active: boolean) { const body = new FormData(); body.set('id', item.id_pruebas_laboratorio); body.set('activo', String(active)); processing = true; const response = await fetch('?/status', { method: 'POST', body }); const result = await response.json(); processing = false; if (response.ok) { await import('$app/navigation').then(({ invalidateAll }) => invalidateAll()); toast.success(i18n.t('notifications.type.success'), { description: i18n.t(active ? 'laboratoryTests.activated' : 'laboratoryTests.deactivated') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t(result?.message ?? 'laboratoryTests.saveError') }); }
  async function remove() { if (!selected) return; const body = new FormData(); body.set('id', selected.id_pruebas_laboratorio); processing = true; const response = await fetch('?/delete', { method: 'POST', body }); processing = false; if (response.ok) { await import('$app/navigation').then(({ invalidateAll }) => invalidateAll()); deleteOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('laboratoryTests.deleted') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t('laboratoryTests.saveError') }); }
</script>

<svelte:head><title>{i18n.t('laboratoryTests.title')} · Sumaq System</title></svelte:head>
<Breadcrumb items={breadcrumbs} />
<section class="flex flex-col gap-5">
  <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-[28px] tracking-[-0.02em] text-ink">{i18n.t('laboratoryTests.title')}</h1><p class="mt-1.5 max-w-[68ch] text-steel">{i18n.t('laboratoryTests.description')}</p></div>{#if canCreate}<Button onclick={() => edit(null)}><Icon name="plus" size={17} />{i18n.t('laboratoryTests.new')}</Button>{/if}</div>
  <Card padding="none" class="overflow-hidden">
    {#if !data.pruebas.length}<div class="py-14 text-center"><Icon name="flask-conical" size={32} class="mx-auto text-stone" /><p class="mt-3 font-semibold text-ink">{i18n.t('laboratoryTests.empty')}</p></div>
    {:else}<div class="hidden overflow-x-auto md:block"><table class="w-full border-collapse"><thead class="bg-surface/70"><tr class="border-b border-hairline text-[11px] font-semibold uppercase tracking-[0.05em] text-stone"><th class="px-5 py-3.5 text-left">{i18n.t('laboratoryTests.name')}</th><th class="px-4 py-3.5 text-left">{i18n.t('laboratoryTests.category')}</th><th class="px-4 py-3.5 text-center">{i18n.t('laboratoryTests.status')}</th>{#if canAny}<th class="px-5 py-3.5 text-right">{i18n.t('laboratoryTests.actions')}</th>{/if}</tr></thead><tbody class="divide-y divide-hairline">{#each data.pruebas as item (item.id_pruebas_laboratorio)}<tr class="hover:bg-surface/55"><td class="px-5 py-3.5"><strong class="text-sm text-ink">{item.nombre}</strong></td><td class="px-4 py-3.5 text-sm text-steel">{item.categoria.nombre}</td><td class="px-4 py-3.5"><div class="flex items-center justify-center gap-2"><Switch checked={item.estado === 1} disabled={!canUpdate || processing} label={`${i18n.t('laboratoryTests.status')}: ${item.nombre}`} onchange={(active) => status(item, active)} /><span class="text-xs text-steel">{i18n.t(item.estado === 1 ? 'laboratoryTests.active' : 'laboratoryTests.inactive')}</span></div></td>{#if canAny}<td class="px-5 py-3.5"><div class="flex justify-end"><DropdownMenu.Root><DropdownMenu.Trigger class="grid size-8 place-items-center rounded-md text-stone hover:bg-surface" aria-label={i18n.t('laboratoryTests.actions')}><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="end">{#if canUpdate}<DropdownMenu.Item onSelect={() => edit(item)}><Icon name="pencil" size={15} />{i18n.t('laboratoryTests.edit')}</DropdownMenu.Item>{/if}{#if canDelete}<DropdownMenu.Item class="text-error focus:bg-error/10 focus:text-error" onSelect={() => { selected = item; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('laboratoryTests.delete')}</DropdownMenu.Item>{/if}</DropdownMenu.Content></DropdownMenu.Root></div></td>{/if}</tr>{/each}</tbody></table></div>
    <div class="divide-y divide-hairline md:hidden">{#each data.pruebas as item (item.id_pruebas_laboratorio)}<article class="p-4"><div class="flex items-start justify-between gap-3"><div><strong class="text-sm text-ink">{item.nombre}</strong><p class="mt-1 text-xs text-steel">{item.categoria.nombre}</p></div>{#if canAny}<DropdownMenu.Root><DropdownMenu.Trigger class="grid size-8 place-items-center rounded-md text-stone"><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="end">{#if canUpdate}<DropdownMenu.Item onSelect={() => edit(item)}><Icon name="pencil" size={15} />{i18n.t('laboratoryTests.edit')}</DropdownMenu.Item>{/if}{#if canDelete}<DropdownMenu.Item class="text-error" onSelect={() => { selected = item; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('laboratoryTests.delete')}</DropdownMenu.Item>{/if}</DropdownMenu.Content></DropdownMenu.Root>{/if}</div><div class="mt-3 flex items-center gap-2 border-t border-hairline pt-3"><Switch checked={item.estado === 1} disabled={!canUpdate || processing} label={item.nombre} onchange={(active) => status(item, active)} /><span class="text-xs text-steel">{i18n.t(item.estado === 1 ? 'laboratoryTests.active' : 'laboratoryTests.inactive')}</span></div></article>{/each}</div>{/if}
  </Card>
</section>

<ConfirmationDialog bind:open={editorOpen} variant="info" icon={selected ? 'pencil' : 'flask-conical'} title={i18n.t(selected ? 'laboratoryTests.editTitle' : 'laboratoryTests.new')} description={i18n.t('laboratoryTests.editorHelp')} confirmLabel={i18n.t('laboratoryTests.save')} cancelLabel={i18n.t('attentions.cancel')} confirmDisabled={processing} onConfirm={submitEditor}><form bind:this={form} method="POST" {action} use:enhance={submit} class="grid gap-4 text-left"><input type="hidden" name="id" value={selected?.id_pruebas_laboratorio ?? ''} /><Select name="fid_categorias_pruebas_laboratorio" label={i18n.t('laboratoryTests.category')} bind:value={categoria} required><option value="">{i18n.t('attentions.selectOption')}</option>{#each data.categorias as item (item.id_categorias_pruebas_laboratorio)}<option value={item.id_categorias_pruebas_laboratorio}>{item.nombre}</option>{/each}</Select><Input name="nombre" label={i18n.t('laboratoryTests.name')} bind:value={nombre} required maxlength={220} /></form></ConfirmationDialog>
<ConfirmationDialog bind:open={deleteOpen} variant="danger" icon="trash-2" title={i18n.t('laboratoryTests.deleteTitle')} description={i18n.t('laboratoryTests.deleteHelp')} confirmLabel={i18n.t('laboratoryTests.delete')} cancelLabel={i18n.t('attentions.cancel')} confirmDisabled={processing} onConfirm={remove} />
