<script lang="ts">
  import { enhance } from '$app/forms';
  import { goto, invalidateAll } from '$app/navigation';
  import type { SubmitFunction } from '@sveltejs/kit';
  import { toast } from 'svelte-sonner';
  import type { PageProps } from './$types';
  import { Breadcrumb, Button, Card, ConfirmationDialog, Icon, Input, Switch, i18n, tienePermiso } from '$lib';
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
  import CatalogSearch from '$lib/components/CatalogSearch.svelte'; import CatalogLoadingOverlay from '$lib/components/CatalogLoadingOverlay.svelte'; import CatalogPagination from '$lib/components/CatalogPagination.svelte';
  import CatalogDuplicateHints from '$lib/components/CatalogDuplicateHints.svelte';

  let { data }: PageProps = $props();
  type Study = (typeof data.estudios)[number];
  let selected = $state<Study | null>(null); let editorOpen = $state(false); let deleteOpen = $state(false); let processing = $state(false); let form = $state<HTMLFormElement>(); let action = $state('?/create'); let nombre = $state('');
  const canCreate = $derived(tienePermiso(data.usuario.permisos, 'administrator.diagnostic_studies.create'));
  const canUpdate = $derived(tienePermiso(data.usuario.permisos, 'administrator.diagnostic_studies.update'));
  const canDelete = $derived(tienePermiso(data.usuario.permisos, 'administrator.diagnostic_studies.delete'));
  const canAny = $derived(canUpdate || canDelete);
  const breadcrumbs = $derived([{ label: i18n.t('nav.dashboard'), href: '/dashboard' }, { label: i18n.t('diagnosticStudies.title') }]);
  function edit(item: Study | null) { selected = item; nombre = item?.nombre ?? ''; action = item ? '?/update' : '?/create'; editorOpen = true; }
  const submit: SubmitFunction = () => { processing = true; return async ({ result, update }) => { processing = false; if (result.type === 'success') { if (!selected) await goto('/administrator/diagnostic-studies', { invalidateAll: true, noScroll: true, replaceState: true }); else await update({ invalidateAll: true, reset: false }); editorOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('diagnosticStudies.saved') }); } else { const message = result.type === 'failure' && typeof result.data?.diagnosticStudyMessage === 'string' ? result.data.diagnosticStudyMessage : 'diagnosticStudies.saveError'; toast.error(i18n.t('notifications.type.error'), { description: i18n.t(message) }); } }; };
  function submitEditor() { if (!form?.reportValidity()) return Promise.reject(new Error('invalid-diagnostic-study')); form.requestSubmit(); return Promise.resolve(); }
  async function status(item: Study, active: boolean) { const body = new FormData(); body.set('id', item.id_estudios_diagnosticos); body.set('activo', String(active)); processing = true; const response = await fetch('?/status', { method: 'POST', body }); processing = false; if (response.ok) { await invalidateAll(); toast.success(i18n.t('notifications.type.success'), { description: i18n.t(active ? 'diagnosticStudies.activated' : 'diagnosticStudies.deactivated') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t('diagnosticStudies.saveError') }); }
  async function remove() { if (!selected) return; const body = new FormData(); body.set('id', selected.id_estudios_diagnosticos); processing = true; const response = await fetch('?/delete', { method: 'POST', body }); processing = false; if (response.ok) { await invalidateAll(); deleteOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('diagnosticStudies.deleted') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t('diagnosticStudies.saveError') }); }
</script>

<svelte:head><title>{i18n.t('diagnosticStudies.title')} · Sumaq System</title></svelte:head>
<Breadcrumb items={breadcrumbs} />
<section class="flex flex-col gap-5">
  <div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-[28px] tracking-[-0.02em] text-ink">{i18n.t('diagnosticStudies.title')}</h1><p class="mt-1.5 max-w-[68ch] text-steel">{i18n.t('diagnosticStudies.description')}</p></div>{#if canCreate}<Button onclick={() => edit(null)}><Icon name="plus" size={17} />{i18n.t('diagnosticStudies.new')}</Button>{/if}</div>
  <CatalogSearch value={data.busqueda} route="/administrator/diagnostic-studies" maxLength={160} />
  <Card padding="none" class="relative overflow-hidden"><CatalogLoadingOverlay />
    {#if !data.estudios.length}<div class="py-14 text-center"><Icon name="image" size={32} class="mx-auto text-stone" /><p class="mt-3 font-semibold text-ink">{i18n.t('diagnosticStudies.empty')}</p></div>
    {:else}<div class="hidden overflow-x-auto md:block"><table class="w-full table-fixed border-collapse text-left text-sm"><colgroup>{#if canAny}<col class="w-[92px]" />{/if}<col /><col class="w-[18%]" /></colgroup><thead class="bg-canvas"><tr class="border-b border-hairline">{#if canAny}<th class="h-10 border-r border-hairline px-3 text-center text-[11px] font-bold uppercase tracking-[0.04em] text-ink">{i18n.t('diagnosticStudies.actions')}</th>{/if}<th class="h-10 border-r border-hairline px-4 text-[11px] font-bold uppercase tracking-[0.04em] text-ink">{i18n.t('diagnosticStudies.name')}</th><th class="h-10 px-4 text-center text-[11px] font-bold uppercase tracking-[0.04em] text-ink">{i18n.t('diagnosticStudies.status')}</th></tr></thead><tbody>{#each data.estudios as item (item.id_estudios_diagnosticos)}<tr class="border-b border-hairline odd:bg-surface/55 even:bg-canvas hover:bg-primary-soft/35">{#if canAny}<td class="border-r border-hairline px-2 py-2.5"><div class="flex items-center justify-center gap-1">{#if canUpdate}<button type="button" title={i18n.t('diagnosticStudies.edit')} class="grid size-7 place-items-center rounded-md text-steel hover:bg-canvas hover:text-primary" onclick={() => edit(item)}><Icon name="pencil" size={15} /></button>{/if}{#if canDelete}<DropdownMenu.Root><DropdownMenu.Trigger class="grid size-7 place-items-center rounded-md text-steel hover:bg-canvas"><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="start"><DropdownMenu.Item class="text-error focus:bg-error/10 focus:text-error" onSelect={() => { selected = item; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('diagnosticStudies.delete')}</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root>{/if}</div></td>{/if}<td class="border-r border-hairline px-4 py-2.5 font-normal text-steel">{item.nombre}</td><td class="px-4 py-2.5"><div class="flex justify-center"><Switch checked={item.estado === 1} disabled={!canUpdate || processing} label={`${i18n.t('diagnosticStudies.status')}: ${item.nombre}`} onchange={(active) => status(item, active)} /></div></td></tr>{/each}</tbody></table></div>
    <div class="divide-y divide-hairline md:hidden">{#each data.estudios as item (item.id_estudios_diagnosticos)}<article class="p-4"><strong class="block truncate text-sm text-ink">{item.nombre}</strong><div class="mt-3 flex items-center justify-between border-t border-hairline pt-3"><Switch checked={item.estado === 1} disabled={!canUpdate || processing} label={item.nombre} onchange={(active) => status(item, active)} />{#if canAny}<div class="flex gap-1">{#if canUpdate}<button type="button" title={i18n.t('diagnosticStudies.edit')} class="grid size-8 place-items-center rounded-md border border-hairline text-steel" onclick={() => edit(item)}><Icon name="pencil" size={16} /></button>{/if}{#if canDelete}<DropdownMenu.Root><DropdownMenu.Trigger class="grid size-8 place-items-center rounded-md border border-hairline text-steel"><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="end"><DropdownMenu.Item class="text-error focus:bg-error/10 focus:text-error" onSelect={() => { selected = item; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('diagnosticStudies.delete')}</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root>{/if}</div>{/if}</div></article>{/each}</div>{/if}
  </Card>
  <CatalogPagination route="/administrator/diagnostic-studies" search={data.busqueda} current={data.estudios.length} total={data.total} previous={data.paginacion.anterior} next={data.paginacion.siguiente} />
</section>

<ConfirmationDialog bind:open={editorOpen} variant="info" icon={selected ? 'pencil' : 'image'} title={i18n.t(selected ? 'diagnosticStudies.editTitle' : 'diagnosticStudies.new')} description={i18n.t('diagnosticStudies.editorHelp')} confirmLabel={i18n.t('diagnosticStudies.save')} cancelLabel={i18n.t('attentions.cancel')} confirmDisabled={processing} onConfirm={submitEditor}><form bind:this={form} method="POST" {action} use:enhance={submit} autocomplete="off" class="text-left"><input type="hidden" name="id" value={selected?.id_estudios_diagnosticos ?? ''} /><div class="relative"><Input name="nombre" autocomplete="off" label={i18n.t('diagnosticStudies.name')} bind:value={nombre} required maxlength={160} /><CatalogDuplicateHints query={nombre} endpoint="/administrator/diagnostic-studies/search" collection="estudios" idKey="id_estudios_diagnosticos" disabled={Boolean(selected)} onSelect={(item) => edit(item as Study)} /></div></form></ConfirmationDialog>
<ConfirmationDialog bind:open={deleteOpen} variant="danger" icon="trash-2" title={i18n.t('diagnosticStudies.deleteTitle')} description={i18n.t('diagnosticStudies.deleteHelp')} confirmLabel={i18n.t('diagnosticStudies.delete')} cancelLabel={i18n.t('attentions.cancel')} confirmDisabled={processing} onConfirm={remove} />
