<script lang="ts">
  import { enhance } from '$app/forms';
  import type { SubmitFunction } from '@sveltejs/kit';
  import { toast } from 'svelte-sonner';
  import type { PageProps } from './$types';
  import { Breadcrumb, Button, Card, ConfirmationDialog, Icon, Input, Switch, i18n, tienePermiso } from '$lib';
  import * as Dialog from '$lib/components/ui/dialog/index.js';
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';

  let { data }: PageProps = $props();
  type Reason = (typeof data.motivos)[number];
  let selected = $state<Reason | null>(null); let editorOpen = $state(false); let deleteOpen = $state(false); let processing = $state(false);
  let nombre = $state(''); let descripcion = $state(''); let editorForm: HTMLFormElement; let statusForm: HTMLFormElement; let deleteForm: HTMLFormElement;
  const canCreate = $derived(tienePermiso(data.usuario.permisos, 'administrator.consultation_reasons.create'));
  const canUpdate = $derived(tienePermiso(data.usuario.permisos, 'administrator.consultation_reasons.update'));
  const canDelete = $derived(tienePermiso(data.usuario.permisos, 'administrator.consultation_reasons.delete'));
  const canAny = $derived(canUpdate || canDelete);
  const breadcrumbs = $derived([{ label: i18n.t('nav.dashboard'), href: '/dashboard' }, { label: i18n.t('consultationReasons.title') }]);
  function edit(reason: Reason | null) { selected = reason; nombre = reason?.nombre ?? ''; descripcion = reason?.descripcion ?? ''; editorOpen = true; }
  const submit: SubmitFunction = () => { processing = true; return async ({ result, update }) => { const ok = result.type === 'success'; if (ok) { await update({ invalidateAll: true, reset: false }); editorOpen = false; deleteOpen = false; toast.success(i18n.t('notifications.type.success'), { description: i18n.t('consultationReasons.saved') }); } else toast.error(i18n.t('notifications.type.error'), { description: i18n.t(result.type === 'failure' && typeof result.data?.reasonMessage === 'string' ? result.data.reasonMessage : 'consultationReasons.saveError') }); processing = false; }; };
  function status(reason: Reason, active: boolean) { selected = reason; requestAnimationFrame(() => { const form = new FormData(statusForm); form.set('activo', String(active)); const input = statusForm.elements.namedItem('activo') as HTMLInputElement; input.value = String(active); statusForm.requestSubmit(); }); }
</script>

<svelte:head><title>{i18n.t('consultationReasons.title')} · Sumaq System</title></svelte:head>
<Breadcrumb items={breadcrumbs} />
<section class="flex flex-col gap-6">
  <div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-[28px] tracking-[-0.02em] text-ink">{i18n.t('consultationReasons.title')}</h1><p class="mt-1.5 max-w-[64ch] text-steel">{i18n.t('consultationReasons.description')}</p></div>{#if canCreate}<Button onclick={() => edit(null)}><Icon name="plus" size={17} />{i18n.t('consultationReasons.new')}</Button>{/if}</div>
  <Card padding="none" class="overflow-hidden">
    {#if !data.motivos.length}<div class="py-14 text-center"><Icon name="stethoscope" size={32} class="mx-auto text-stone" /><p class="mt-3 font-semibold text-ink">{i18n.t('consultationReasons.empty')}</p></div>
    {:else}
      <div class="hidden overflow-x-auto md:block">
        <table class="w-full min-w-[720px] border-collapse text-left">
          <thead class="bg-surface/70"><tr class="border-b border-hairline text-[11px] font-semibold uppercase tracking-[0.05em] text-stone"><th class="px-5 py-3.5">{i18n.t('consultationReasons.name')}</th><th class="px-4 py-3.5">{i18n.t('consultationReasons.reasonDescription')}</th><th class="px-4 py-3.5 text-center">{i18n.t('consultationReasons.status')}</th>{#if canAny}<th class="px-5 py-3.5 text-right">{i18n.t('consultationReasons.actions')}</th>{/if}</tr></thead>
          <tbody class="divide-y divide-hairline">{#each data.motivos as reason (reason.id_motivos_consulta)}<tr class="transition-colors hover:bg-surface/55"><td class="px-5 py-4"><div class="flex min-w-0 items-center gap-3"><span class="grid size-9 shrink-0 place-items-center rounded-md bg-primary-soft text-primary"><Icon name="stethoscope" size={18} /></span><strong class="block max-w-[300px] truncate text-sm text-ink">{reason.nombre}</strong></div></td><td class="px-4 py-4"><p class="max-w-[500px] truncate text-sm text-steel">{reason.descripcion || i18n.t('consultationReasons.noDescription')}</p></td><td class="px-4 py-4"><div class="flex items-center justify-center gap-2"><Switch checked={reason.estado === 1} disabled={!canUpdate || processing} label={`${i18n.t('consultationReasons.status')}: ${reason.nombre}`} onchange={(active) => status(reason, active)} /><span class="text-xs text-steel">{i18n.t(reason.estado === 1 ? 'consultationReasons.active' : 'consultationReasons.inactive')}</span></div></td>{#if canAny}<td class="px-5 py-4"><div class="flex justify-end"><DropdownMenu.Root><DropdownMenu.Trigger disabled={processing} class="grid size-8 place-items-center rounded-md border border-transparent text-stone transition-colors hover:border-hairline hover:bg-surface hover:text-ink disabled:pointer-events-none disabled:opacity-40" aria-label={`${i18n.t('consultationReasons.actions')}: ${reason.nombre}`}><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="end" class="min-w-[160px]">{#if canUpdate}<DropdownMenu.Item disabled={processing} onSelect={() => edit(reason)}><Icon name="pencil" size={15} /><span>{i18n.t('consultationReasons.edit')}</span></DropdownMenu.Item>{/if}{#if canUpdate && canDelete}<DropdownMenu.Separator />{/if}{#if canDelete}<DropdownMenu.Item disabled={processing} class="text-error focus:bg-error/10 focus:text-error" onSelect={() => { selected = reason; deleteOpen = true; }}><Icon name="trash-2" size={15} /><span>{i18n.t('consultationReasons.delete')}</span></DropdownMenu.Item>{/if}</DropdownMenu.Content></DropdownMenu.Root></div></td>{/if}</tr>{/each}</tbody>
        </table>
      </div>
      <div class="divide-y divide-hairline md:hidden">{#each data.motivos as reason (reason.id_motivos_consulta)}<article class="p-4"><div class="flex min-w-0 items-start gap-3"><span class="grid size-9 shrink-0 place-items-center rounded-md bg-primary-soft text-primary"><Icon name="stethoscope" size={18} /></span><div class="min-w-0 flex-1"><strong class="block truncate text-sm text-ink">{reason.nombre}</strong><p class="mt-1 line-clamp-2 text-xs leading-5 text-steel">{reason.descripcion || i18n.t('consultationReasons.noDescription')}</p></div></div><div class="mt-4 flex items-center justify-between gap-3 border-t border-hairline pt-3"><div class="flex items-center gap-2"><Switch checked={reason.estado === 1} disabled={!canUpdate || processing} label={`${i18n.t('consultationReasons.status')}: ${reason.nombre}`} onchange={(active) => status(reason, active)} /><span class="text-xs text-steel">{i18n.t(reason.estado === 1 ? 'consultationReasons.active' : 'consultationReasons.inactive')}</span></div>{#if canAny}<DropdownMenu.Root><DropdownMenu.Trigger disabled={processing} class="grid size-8 place-items-center rounded-md border border-transparent text-stone hover:border-hairline hover:bg-surface" aria-label={`${i18n.t('consultationReasons.actions')}: ${reason.nombre}`}><Icon name="ellipsis" size={18} /></DropdownMenu.Trigger><DropdownMenu.Content align="end">{#if canUpdate}<DropdownMenu.Item onSelect={() => edit(reason)}><Icon name="pencil" size={15} />{i18n.t('consultationReasons.edit')}</DropdownMenu.Item>{/if}{#if canUpdate && canDelete}<DropdownMenu.Separator />{/if}{#if canDelete}<DropdownMenu.Item class="text-error focus:bg-error/10 focus:text-error" onSelect={() => { selected = reason; deleteOpen = true; }}><Icon name="trash-2" size={15} />{i18n.t('consultationReasons.delete')}</DropdownMenu.Item>{/if}</DropdownMenu.Content></DropdownMenu.Root>{/if}</div></article>{/each}</div>
    {/if}
  </Card>
</section>
<form bind:this={statusForm} class="hidden" method="POST" action="?/status" use:enhance={submit}><input name="id" value={selected?.id_motivos_consulta ?? ''} /><input name="activo" /></form>
<form bind:this={deleteForm} class="hidden" method="POST" action="?/delete" use:enhance={submit}><input name="id" value={selected?.id_motivos_consulta ?? ''} /></form>
<Dialog.Root bind:open={editorOpen}><Dialog.Content class="sm:max-w-[620px]"><Dialog.Header><Dialog.Title>{i18n.t(selected ? 'consultationReasons.edit' : 'consultationReasons.new')}</Dialog.Title><Dialog.Description>{i18n.t('consultationReasons.editorHelp')}</Dialog.Description></Dialog.Header><form bind:this={editorForm} method="POST" action={selected ? '?/update' : '?/create'} use:enhance={submit} class="grid gap-4"><input type="hidden" name="id" value={selected?.id_motivos_consulta ?? ''} /><Input name="nombre" label={i18n.t('consultationReasons.name')} bind:value={nombre} required maxlength={120} /><label><span class="mb-1.5 block text-sm font-medium text-charcoal">{i18n.t('consultationReasons.reasonDescription')}</span><textarea name="descripcion" bind:value={descripcion} maxlength="500" rows="4" class="w-full rounded-md border border-hairline-strong bg-canvas px-3.5 py-3 text-base text-ink"></textarea></label><Dialog.Footer><Button type="button" variant="secondary" onclick={() => (editorOpen = false)}>{i18n.t('attentions.cancel')}</Button><Button type="submit" loading={processing}>{i18n.t('consultationReasons.save')}</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>
<ConfirmationDialog bind:open={deleteOpen} variant="danger" title={i18n.t('consultationReasons.deleteTitle')} description={i18n.t('consultationReasons.deleteHelp')} confirmLabel={i18n.t('consultationReasons.delete')} cancelLabel={i18n.t('attentions.cancel')} onConfirm={() => { deleteForm.requestSubmit(); return Promise.resolve(); }} />
